"""
scripts/build_dashboard.py — generate dashboard.html: a single, self-contained,
zero-server view of the whole pipeline. Regenerated by the daily and weekly
jobs; open the file in any browser.

Sections: regime + health header, the filtering funnel, today's alerts +
analyst verdicts, tag board, top-conviction table (sortable, sparklines),
open positions vs their plans, forward journal.
"""

from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from data.cache import load_ohlcv

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dashboard.html")

TAG_COLORS = {"CONFIRMED": "#34d399", "ANTICIPATION": "#22d3ee",
              "EXTENDED": "#fbbf24", "BROKEN": "#f87171", "WATCH": "#64748b"}


def _read_csv(name: str) -> pd.DataFrame:
    p = os.path.join(ROOT, name)
    return pd.read_csv(p) if os.path.exists(p) else pd.DataFrame()


def sparkline(sym: str, days: int = 120) -> str:
    df = load_ohlcv(sym)
    if df is None or len(df) < 20:
        return ""
    closes = df["close"].tail(days).to_numpy()
    lo, hi = float(closes.min()), float(closes.max())
    rng = (hi - lo) or 1.0
    w, h = 110, 30
    pts = " ".join(f"{i * w / (len(closes) - 1):.1f},{h - 2 - (c - lo) / rng * (h - 6):.1f}"
                   for i, c in enumerate(closes))
    up = closes[-1] >= closes[0]
    color = "#34d399" if up else "#f87171"
    return (f'<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}">'
            f'<polyline fill="none" stroke="{color}" stroke-width="1.6" points="{pts}"/></svg>')


def build() -> None:
    universe = _read_csv("universe.csv")
    focus = _read_csv("focus_list.csv")
    ranked = _read_csv("shortlist_ranked.csv")
    positions = _read_csv("positions.csv")
    journal = _read_csv(os.path.join("journal", "signals_journal.csv"))

    state_path = os.path.join(ROOT, "state", "tags_state.json")
    tags = {}
    if os.path.exists(state_path):
        with open(state_path, "r", encoding="utf-8") as f:
            tags = json.load(f).get("tags", {})
    tag_counts = pd.Series(list(tags.values())).value_counts().to_dict() if tags else {}

    # regime + health
    bench = load_ohlcv("NIFTY50")
    regime_defensive, bench_age = False, 99
    if bench is not None and len(bench) > 150:
        sma150 = bench["close"].rolling(150).mean().iloc[-1]
        regime_defensive = float(bench["close"].iloc[-1]) < float(sma150)
        bench_age = (datetime.now() - bench["date"].iloc[-1]).days
    health_ok = bench_age <= 5 and len(tags) > 400

    # alerts + analyst verdicts from daily_alerts.md
    alerts_html, verdicts_html, scan_date = "", "", ""
    ap = os.path.join(ROOT, "daily_alerts.md")
    if os.path.exists(ap):
        raw = open(ap, "r", encoding="utf-8").read()
        m = re.search(r"Daily scan . (.+)", raw)
        scan_date = m.group(1).strip() if m else ""
        bullets = re.findall(r"^- \*\*(.+?)\*\*: (.+)$", raw, re.M)
        if bullets:
            alerts_html = "".join(
                f'<div class="alert"><span class="ak">{k}</span><span>{v}</span></div>'
                for k, v in bullets)
        else:
            first = re.search(r"^No transitions.*$|^Baseline established.*$", raw, re.M)
            alerts_html = f'<div class="quiet">{first.group(0) if first else "No alerts"}</div>'
        vm = re.search(r"## AI analyst verdicts\n(.*?)(?=\n## |\Z)", raw, re.S)
        if vm:
            verdicts_html = ('<div class="card"><h2>AI analyst verdicts</h2><pre class="memo">'
                             + vm.group(1).strip()[:3000] + "</pre></div>")

    # funnel
    shortlist_n = tag_counts.get("CONFIRMED", 0) + tag_counts.get("ANTICIPATION", 0)
    alerts_n = len(re.findall(r"^- \*\*", open(ap, encoding="utf-8").read(), re.M)) if os.path.exists(ap) else 0
    funnel = [
        ("NSE index universe", len(universe), "official constituents, weekly"),
        ("Watched nightly", len(tags), "enough history for a mechanical read"),
        ("Focus list", len(focus), "top relative strength (reporting only)"),
        ("Actionable tags", shortlist_n, "CONFIRMED + ANTICIPATION today"),
        ("Alerts tonight", alerts_n, "state TRANSITIONS only"),
    ]
    fmax = max(n for _, n, _ in funnel) or 1
    funnel_html = "".join(
        f'<div class="frow"><div class="flabel">{label}<span class="fsub">{sub}</span></div>'
        f'<div class="fbarwrap"><div class="fbar" style="width:{max(n / fmax * 100, 2):.1f}%"></div>'
        f'<span class="fnum">{n}</span></div></div>'
        for label, n, sub in funnel)

    # tag board
    tag_html = "".join(
        f'<div class="chip" style="border-color:{TAG_COLORS.get(t, "#475569")}">'
        f'<b style="color:{TAG_COLORS.get(t, "#94a3b8")}">{t}</b><span>{c}</span></div>'
        for t, c in sorted(tag_counts.items(), key=lambda x: -x[1]))

    # conviction table (top 25 non-vetoed + vetoed pile)
    rows_html = ""
    if not ranked.empty:
        top = ranked[~ranked["vetoed"]].head(25)
        for _, r in top.iterrows():
            score = float(r["score"]) if pd.notna(r["score"]) else 0
            rows_html += (
                f'<tr><td class="sym">{r["symbol"]}</td>'
                f'<td class="dim">{str(r["industry"])[:26]}</td>'
                f'<td><span class="pill" style="border-color:{TAG_COLORS.get(r["tag"], "#475569")};'
                f'color:{TAG_COLORS.get(r["tag"], "#94a3b8")}">{r["tag"]}</span></td>'
                f'<td class="dim">{("-" if "untagged" in str(r["archetypes"]) else str(r["archetypes"]))[:24]}</td>'
                f'<td><div class="scorebar"><div style="width:{score}%"></div></div>'
                f'<span class="scoretxt">{score:.0f}</span></td>'
                f'<td class="dim">{r["coverage"]:.0f}%</td>'
                f'<td>{sparkline(r["symbol"])}</td></tr>')
        vetoed = ranked[ranked["vetoed"]]
        veto_html = "".join(
            f'<div class="vetoed"><b>{r["symbol"]}</b> {str(r["veto_reasons"])[:90]}</div>'
            for _, r in vetoed.iterrows())
    else:
        veto_html = ""

    # positions
    pos_html = ""
    for _, p in positions.iterrows():
        df = load_ohlcv(p["symbol"])
        last = float(df["close"].iloc[-1]) if df is not None else float(p["entry_price"])
        entry, stop = float(p["entry_price"]), float(p["stop_current"])
        risk = entry - float(p["initial_stop"])
        partial = entry + 2.5 * risk
        be = entry + 1.5 * risk
        pnl = (last / entry - 1) * 100
        prog = max(0.0, min(1.0, (last - stop) / (partial - stop))) * 100
        pnl_c = "#34d399" if pnl >= 0 else "#f87171"
        pos_html += (
            f'<div class="poscard"><div class="posrow"><b>{p["symbol"]}</b>'
            f'<span style="color:{pnl_c};font-weight:600">{pnl:+.1f}%</span></div>'
            f'<div class="posrow dim"><span>{int(p["shares_trading"]) + int(p["shares_core"])} sh @ {entry:.2f}</span>'
            f'<span>last {last:.2f}</span></div>'
            f'<div class="track"><div class="trackfill" style="width:{prog:.1f}%"></div></div>'
            f'<div class="posrow tiny"><span>stop {stop:.2f}</span><span>b/e {be:.2f}</span>'
            f'<span>partial {partial:.2f}</span></div>'
            f'<div class="tiny dim">{sparkline(p["symbol"])}</div></div>')

    # journal
    j_html = ""
    if not journal.empty:
        for _, r in journal.tail(8).iloc[::-1].iterrows():
            j_html += (f'<tr><td class="dim">{str(r["logged_at"])[:10]}</td>'
                       f'<td class="sym">{r["symbol"]}</td><td>{r["kind"]}</td>'
                       f'<td class="dim">{r.get("old_tag", "")} -> {r.get("new_tag", "")}</td></tr>')
    else:
        j_html = '<tr><td colspan="4" class="quiet">No signals journaled yet — the clock started 2026-07-05.</td></tr>'

    regime_badge = ('<span class="badge" style="background:#fbbf2422;color:#fbbf24">DEFENSIVE - half size (NIFTY &lt; 150-DMA)</span>'
                    if regime_defensive else
                    '<span class="badge" style="background:#34d39922;color:#34d399">NORMAL RISK</span>')
    health_badge = ('<span class="badge" style="background:#34d39922;color:#34d399">HEALTH OK</span>'
                    if health_ok else
                    '<span class="badge" style="background:#f8717122;color:#f87171">HEALTH CHECK FAILED</span>')

    html = TEMPLATE
    for token, value in {
        "%%GENERATED%%": datetime.now().strftime("%d %b %Y, %H:%M"),
        "%%SCANDATE%%": scan_date, "%%REGIME%%": regime_badge, "%%HEALTH%%": health_badge,
        "%%FUNNEL%%": funnel_html, "%%TAGS%%": tag_html, "%%ALERTS%%": alerts_html,
        "%%VERDICTS%%": verdicts_html, "%%ROWS%%": rows_html, "%%VETOED%%": veto_html,
        "%%POSITIONS%%": pos_html or '<div class="quiet">No open positions tracked.</div>',
        "%%JOURNAL%%": j_html,
    }.items():
        html = html.replace(token, str(value))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"dashboard -> {OUT}")


TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Golden Stock System</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;800&display=swap" rel="stylesheet">
<style>
:root{--bg:#0a0e16;--card:#111827;--line:#1f2937;--txt:#e6ebf4;--dim:#8b98ac;--acc:#34d399}
*{box-sizing:border-box;margin:0}
body{background:var(--bg);color:var(--txt);font-family:Inter,system-ui,sans-serif;padding:28px;max-width:1180px;margin:0 auto}
h1{font-size:22px;font-weight:800;letter-spacing:-.3px}
h2{font-size:13px;font-weight:600;color:var(--dim);text-transform:uppercase;letter-spacing:1.2px;margin-bottom:14px}
.top{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px;margin-bottom:6px}
.sub{color:var(--dim);font-size:13px;margin-bottom:22px}
.badge{padding:5px 12px;border-radius:999px;font-size:12px;font-weight:600;margin-left:8px}
.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}
.card{background:linear-gradient(180deg,#111827f2,#0d1420f2);border:1px solid var(--line);border-radius:18px;padding:20px;margin-bottom:18px}
.frow{display:flex;align-items:center;gap:14px;margin:10px 0}
.flabel{width:220px;font-size:13px;font-weight:500}
.fsub{display:block;color:var(--dim);font-size:11px;font-weight:400}
.fbarwrap{flex:1;display:flex;align-items:center;gap:10px}
.fbar{height:14px;border-radius:7px;background:linear-gradient(90deg,#34d399,#22d3ee)}
.fnum{font-weight:800;font-size:15px;min-width:40px}
.chip{display:inline-flex;gap:8px;align-items:center;border:1px solid;border-radius:999px;padding:6px 14px;margin:4px 6px 4px 0;font-size:13px;background:#0d1420}
.chip span{color:var(--dim)}
.alert{display:flex;gap:10px;padding:10px 12px;border-left:3px solid var(--acc);background:#0d1a16;border-radius:0 10px 10px 0;margin:8px 0;font-size:13px}
.ak{font-weight:700;color:var(--acc);white-space:nowrap}
.quiet{color:var(--dim);font-size:13px;padding:8px 0}
table{width:100%;border-collapse:collapse;font-size:13px}
th{color:var(--dim);text-align:left;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.8px;padding:8px 10px;border-bottom:1px solid var(--line);cursor:pointer}
td{padding:9px 10px;border-bottom:1px solid #16202f}
tr:hover td{background:#0d1420}
.sym{font-weight:700}
.dim{color:var(--dim)}
.pill{border:1px solid;border-radius:999px;padding:3px 10px;font-size:11px;font-weight:600}
.scorebar{display:inline-block;width:90px;height:8px;background:#1a2434;border-radius:4px;vertical-align:middle;margin-right:8px}
.scorebar div{height:8px;border-radius:4px;background:linear-gradient(90deg,#a78bfa,#34d399)}
.scoretxt{font-weight:700}
.vetoed{font-size:12px;color:#f87171;padding:6px 10px;background:#1a0f12;border-radius:8px;margin:6px 0}
.poscard{border:1px solid var(--line);border-radius:14px;padding:14px;margin-bottom:12px;background:#0d1420}
.posrow{display:flex;justify-content:space-between;margin:3px 0;font-size:13px}
.tiny{font-size:11px}
.track{height:8px;background:#1a2434;border-radius:4px;margin:10px 0 6px}
.trackfill{height:8px;border-radius:4px;background:linear-gradient(90deg,#f87171,#fbbf24,#34d399)}
.memo{white-space:pre-wrap;font-family:inherit;font-size:13px;line-height:1.65;color:var(--txt)}
input{background:#0d1420;border:1px solid var(--line);border-radius:10px;color:var(--txt);padding:8px 14px;font-size:13px;width:220px;margin-bottom:10px}
footer{color:#5a6b82;font-size:11px;margin-top:26px;line-height:1.7}
@media(max-width:900px){.grid{grid-template-columns:1fr}}
</style></head><body>
<div class="top"><h1>Golden Stock System</h1><div>%%REGIME%%%%HEALTH%%</div></div>
<div class="sub">Generated %%GENERATED%% &middot; last scan %%SCANDATE%% &middot; alerts fire on state transitions only</div>

<div class="card"><h2>The filtering funnel &mdash; tonight</h2>%%FUNNEL%%</div>

<div class="grid"><div>
<div class="card"><h2>Tonight's alerts</h2>%%ALERTS%%</div>
%%VERDICTS%%
<div class="card"><h2>Top conviction &mdash; non-vetoed</h2>
<input id="q" placeholder="filter symbols..." onkeyup="flt()">
<table id="tbl"><thead><tr><th>Symbol</th><th>Industry</th><th>Tag</th><th>Archetype</th><th>Conviction</th><th>Cov</th><th>120d</th></tr></thead>
<tbody>%%ROWS%%</tbody></table>
<div style="margin-top:12px">%%VETOED%%</div></div>
</div><div>
<div class="card"><h2>Tag board (whole universe)</h2>%%TAGS%%</div>
<div class="card"><h2>Open positions vs their plans</h2>%%POSITIONS%%</div>
<div class="card"><h2>Forward journal (latest)</h2>
<table><thead><tr><th>Date</th><th>Symbol</th><th>Signal</th><th>Move</th></tr></thead>
<tbody>%%JOURNAL%%</tbody></table></div>
</div></div>

<footer>Data: NSE index constituents &middot; Yahoo Finance OHLCV (verified vs Zerodha) &middot; screener.in public pages &middot; NSE announcements RSS &middot; Google News.
Decision support only &mdash; not investment advice. Validated design: entries technical-only; fundamentals = vetoes + context (see VALIDATION_REPORT.md).</footer>
<script>
function flt(){var q=document.getElementById('q').value.toUpperCase();
document.querySelectorAll('#tbl tbody tr').forEach(function(r){
r.style.display=r.cells[0].innerText.toUpperCase().indexOf(q)>-1?'':'none';});}
</script></body></html>"""


if __name__ == "__main__":
    build()
