"""
scripts/build_dashboard.py — v2: a full command-center SPA in one generated
file. Tabs: Overview / Screener / Positions / Journal / Validation, plus a
click-through stock drawer with real candlestick charts (TradingView
lightweight-charts via CDN), moving averages, volume, plan price-lines,
quarterly-profit bars, debt and shareholding trends.

All data is embedded at build time (~3MB JSON): OHLC for the shortlist +
positions, close series for the whole focus list, fundamental series from
the screener cache, journal, baseline equity curve, matrix verdicts.
Regenerated by the daily and weekly jobs. Open dashboard.html in a browser.
"""

from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from data.cache import load_ohlcv
from data.screener_fetch import load_company
from paper_trader import summarize as paper_summary


def _market_cap(sym: str):
    """Current market cap (Cr) from the screener cache — available for the
    whole universe (fetched during the PIT backfill), so cap tiers are
    classified consistently, not just for the shortlist."""
    raw = load_company(sym)
    if not raw:
        return None
    mc = (raw.get("top_ratios") or {}).get("Market Cap")
    try:
        return float(mc) if mc is not None else None
    except (TypeError, ValueError):
        return None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dashboard.html")


def _read_csv(name: str) -> pd.DataFrame:
    p = os.path.join(ROOT, name)
    return pd.read_csv(p) if os.path.exists(p) else pd.DataFrame()


def _ohlc(sym: str, days: int = 260) -> list:
    df = load_ohlcv(sym)
    if df is None or len(df) < 30:
        return []
    t = df.tail(days)
    return [[str(d.date()), round(o, 2), round(h, 2), round(l, 2), round(c, 2), int(v)]
            for d, o, h, l, c, v in zip(t["date"], t["open"], t["high"],
                                        t["low"], t["close"], t["volume"])]


def _closes(sym: str, days: int = 120) -> list:
    df = load_ohlcv(sym)
    if df is None or len(df) < 20:
        return []
    return [round(float(c), 2) for c in df["close"].tail(days)]


def _fund_series(sym: str) -> dict:
    raw = load_company(sym)
    if not raw:
        return {}
    out = {}
    q = raw.get("quarters", {})
    if q.get("rows"):
        cols = q.get("columns", [])[-12:]
        np_row = (q["rows"].get("Net Profit") or [])[-12:]
        opm = (q["rows"].get("OPM %") or q["rows"].get("Financing Margin %") or [])[-12:]
        out["q_labels"] = cols
        out["np"] = np_row
        out["opm"] = opm
    bs = raw.get("balance_sheet", {})
    if bs.get("rows"):
        out["bs_labels"] = bs.get("columns", [])[-10:]
        out["debt"] = (bs["rows"].get("Borrowings") or [])[-10:]
    sh = raw.get("shareholding", {})
    if sh.get("rows"):
        out["sh_labels"] = sh.get("columns", [])[-12:]
        out["prom"] = (sh["rows"].get("Promoters") or [])[-12:]
        out["fii"] = (sh["rows"].get("FIIs") or [])[-12:]
        out["dii"] = (sh["rows"].get("DIIs") or [])[-12:]
    return out


def build_payload() -> dict:
    universe = _read_csv("universe.csv")
    focus = _read_csv("focus_list.csv")
    ranked = _read_csv("shortlist_ranked.csv")
    funds = _read_csv("fundamentals_flat.csv")
    positions = _read_csv("positions.csv")
    journal = _read_csv(os.path.join("journal", "signals_journal.csv"))
    outcomes = _read_csv(os.path.join("journal", "journal_outcomes.csv"))
    details = {}
    dpath = os.path.join(ROOT, "shortlist_details.json")
    if os.path.exists(dpath):
        details = json.load(open(dpath, encoding="utf-8"))
    # alert-time details from the nightly scan — every alerted name gets a
    # full drawer, not just the weekly shortlist; alert data is fresher so
    # it wins on collision
    adpath = os.path.join(ROOT, "state", "alert_details.json")
    if os.path.exists(adpath):
        try:
            details.update(json.load(open(adpath, encoding="utf-8")))
        except ValueError:
            pass
    ai_picks = {}
    ppath = os.path.join(ROOT, "ai_picks.json")
    if os.path.exists(ppath):
        ai_picks = json.load(open(ppath, encoding="utf-8"))
    # news-first discovery radar (state/news_radar.json, written by the scan)
    radar = {}
    rpath = os.path.join(ROOT, "state", "news_radar.json")
    if os.path.exists(rpath):
        try:
            radar = json.load(open(rpath, encoding="utf-8"))
        except ValueError:
            pass
    company_by_sym = dict(zip(universe.get("symbol", []), universe.get("company", [])))

    state_path = os.path.join(ROOT, "state", "tags_state.json")
    tags = {}
    if os.path.exists(state_path):
        tags = json.load(open(state_path, encoding="utf-8")).get("tags", {})

    bench = load_ohlcv("NIFTY50")
    nifty, regime_defensive, bench_age = [], False, 99
    if bench is not None and len(bench) > 160:
        b = bench.tail(500).copy()
        b["sma"] = bench["close"].rolling(150).mean().tail(500)
        nifty = [[str(d.date()), round(float(c), 1),
                  round(float(s), 1) if pd.notna(s) else None]
                 for d, c, s in zip(b["date"], b["close"], b["sma"])]
        regime_defensive = bool(b["close"].iloc[-1] < b["sma"].iloc[-1])
        bench_age = (datetime.now() - bench["date"].iloc[-1]).days

    # alerts + verdicts
    alerts, verdicts, scan_date = [], "", ""
    ap = os.path.join(ROOT, "daily_alerts.md")
    if os.path.exists(ap):
        raw = open(ap, encoding="utf-8").read()
        m = re.search(r"Daily scan . (.+)", raw)
        scan_date = m.group(1).strip() if m else ""
        # buy-type lines carry an entry-fidelity label ("**KIND** [STATUS]: SYM")
        # since ~2026-07-14 — the old strict "**KIND**:" pattern dropped exactly
        # the buy alerts from the Tonight panel (audit catch 2026-07-18)
        alerts = [{"kind": k, "text": (f"[{s}] " if s else "") + v}
                  for k, s, v in
                  re.findall(r"^- \*\*(.+?)\*\*(?:\s*\[([^\]]*)\])?: (.+)$", raw, re.M)]
        vm = re.search(r"## AI analyst verdicts\n(.*?)(?=\n## |\Z)", raw, re.S)
        verdicts = vm.group(1).strip()[:4000] if vm else ""

    # screener rows: focus list enriched with fundamentals where known
    fund_by_sym = {r["symbol"]: r for _, r in funds.iterrows()} if not funds.empty else {}
    score_by_sym = dict(zip(ranked.get("symbol", []), ranked.get("score", [])))
    veto_by_sym = dict(zip(ranked.get("symbol", []), ranked.get("vetoed", [])))
    arch_by_sym = dict(zip(ranked.get("symbol", []), ranked.get("archetypes", [])))
    TIER = {"microcap250": "Micro", "smallcap250": "Small", "midcap150": "Mid"}

    def cap_tier(mcap, idx_src):
        # actual market cap wins; index membership is the fallback label
        if mcap is not None and pd.notna(mcap):
            m = float(mcap)
            return "Micro" if m < 2000 else "Small" if m < 12000 else "Mid" if m < 50000 else "Large"
        return TIER.get(str(idx_src), "")

    screener_rows, closes = [], {}
    for _, r in focus.iterrows():
        sym = r["symbol"]
        f = fund_by_sym.get(sym, {})
        arch = str(arch_by_sym.get(sym, ""))
        # market cap from the full-universe screener cache (consistent), with
        # the shortlist flat file as a secondary source
        mcap = _market_cap(sym)
        if mcap is None:
            mcap = f.get("market_cap_cr")
        closes[sym] = _closes(sym)
        # price from tonight's cache — the focus snapshot's last_close is a
        # WEEKLY artifact and goes stale within a day (user-caught 2026-07-09)
        live_close = closes[sym][-1] if closes[sym] else (
            round(float(r["last_close"]), 2) if pd.notna(r.get("last_close")) else None)
        screener_rows.append({
            "sym": sym, "company": str(company_by_sym.get(sym, ""))[:40],
            "ind": str(r.get("industry", ""))[:30],
            # tonight's state wins over the weekly focus snapshot (freshness)
            "tag": tags.get(sym, r.get("tag", "")),
            "tier": cap_tier(mcap, r.get("index_source", "")),
            "mcap": round(float(mcap), 0) if mcap is not None and pd.notna(mcap) else None,
            "rs": round(float(r["rs_pctile"]), 1) if pd.notna(r.get("rs_pctile")) else None,
            "close": live_close,
            "turn": round(float(r["turnover_cr"]), 1) if pd.notna(r.get("turnover_cr")) else None,
            "score": round(float(score_by_sym[sym]), 1) if sym in score_by_sym and pd.notna(score_by_sym[sym]) else None,
            "veto": bool(veto_by_sym.get(sym, False)),
            "arch": "" if "untagged" in arch else arch[:26],
            "roce": f.get("roce_pct"), "pe": f.get("pe"),
            "pgttm": f.get("profit_growth_ttm"),
            "focus": True,
        })

    # the scan watches (and alerts from) the WHOLE tagged universe — the
    # screener must show those names too, or alerted stocks are unfindable
    # (user-caught 2026-07-10). Non-focus names carry no RS percentile (that
    # is a focus-list artifact) but get tag/price/cap/score like everyone.
    ind_by_sym = dict(zip(universe.get("symbol", []), universe.get("industry", [])))
    focus_syms = set(focus["symbol"]) if not focus.empty else set()
    for sym, tg in tags.items():
        if sym in focus_syms:
            continue
        f = fund_by_sym.get(sym, {})
        closes[sym] = _closes(sym)
        live_close = closes[sym][-1] if closes[sym] else None
        mcap = _market_cap(sym)
        if mcap is None:
            mcap = f.get("market_cap_cr")
        arch = str(arch_by_sym.get(sym, ""))
        screener_rows.append({
            "sym": sym, "company": str(company_by_sym.get(sym, ""))[:40],
            "ind": str(ind_by_sym.get(sym, ""))[:30],
            "tag": tg,
            "tier": cap_tier(mcap, ""),
            "mcap": round(float(mcap), 0) if mcap is not None and pd.notna(mcap) else None,
            "rs": None,
            "close": live_close,
            "turn": None,
            "score": round(float(score_by_sym[sym]), 1) if sym in score_by_sym and pd.notna(score_by_sym[sym]) else None,
            "veto": bool(veto_by_sym.get(sym, False)),
            "arch": "" if "untagged" in arch else arch[:26],
            "roce": f.get("roce_pct"), "pe": f.get("pe"),
            "pgttm": f.get("profit_growth_ttm"),
            "focus": False,
        })

    # detail data: OHLC + fundamentals for shortlist + positions + paper book
    # + every recently-alerted name (details now includes alert_details.json)
    paper_pos = _read_csv("paper_positions.csv")
    detail_syms = (list(ranked.get("symbol", [])) + list(positions.get("symbol", []))
                   + list(paper_pos.get("symbol", [])) + list(details.keys()))
    ohlc = {s: _ohlc(s) for s in dict.fromkeys(detail_syms)}
    fund_series = {s: _fund_series(s) for s in dict.fromkeys(detail_syms)}

    pos_rows = []
    for _, p in positions.iterrows():
        df = load_ohlcv(p["symbol"])
        last = float(df["close"].iloc[-1]) if df is not None else float(p["entry_price"])
        risk = float(p["entry_price"]) - float(p["initial_stop"])
        pos_rows.append({
            "sym": p["symbol"], "entry": float(p["entry_price"]),
            "stop": float(p["stop_current"]), "last": round(last, 2),
            "be": round(float(p["entry_price"]) + 1.5 * risk, 2),
            "partial": round(float(p["entry_price"]) + 2.5 * risk, 2),
            "shares": int(p["shares_trading"]) + int(p["shares_core"]),
            "pnl": round((last / float(p["entry_price"]) - 1) * 100, 2),
            "notes": str(p.get("notes", "")),
        })

    j_rows = []
    journal_total = 0 if journal.empty else len(journal)
    if not journal.empty:
        for _, r in journal.tail(50).iloc[::-1].iterrows():
            j_rows.append({"d": str(r["logged_at"])[:16], "sym": r["symbol"],
                           "kind": r["kind"], "old": str(r.get("old_tag", "")),
                           "new": str(r.get("new_tag", ""))[:40]})
    out_stats = {}
    if not outcomes.empty:
        rvals = pd.to_numeric(outcomes.get("r_to_date"), errors="coerce").dropna()
        out_stats = {"n": len(outcomes),
                     "open": int((outcomes["status"] == "open").sum()),
                     "stopped": int((outcomes["status"] == "stopped").sum()),
                     "exp": round(float(rvals.mean()), 2) if len(rvals) else None}

    # journal scorecard: every buy-type signal marked to market (Journal tab)
    def _num(v, nd=2):
        v = pd.to_numeric(pd.Series([v]), errors="coerce").iloc[0]
        return round(float(v), nd) if pd.notna(v) else None
    score_rows = []
    if not outcomes.empty:
        seen_sc: dict = {}   # symbol -> how many newer rows exist (re-alert marker)
        for _, r in outcomes.iloc[::-1].iterrows():
            sym = str(r["symbol"])
            score_rows.append({
                "d": str(r["logged_at"])[:16], "sym": sym,
                "kind": str(r.get("kind", "")), "entry": _num(r.get("close")),
                "stop": _num(r.get("stop_suggested")),
                "ret": _num(r.get("return_to_date_pct"), 1),
                "r": _num(r.get("r_to_date")), "maxr": _num(r.get("max_favorable_R")),
                "status": str(r.get("status", "")),
                "conv": _num(r.get("conviction_score"), 0),
                # coverage: <60% means the number is a coverage-limited
                # "technical read", not a full 8-question conviction score
                "cov": _num(r.get("coverage_pct"), 0),
                # 0 = newest signal for this symbol; 1,2,… = earlier re-alerts
                "re": seen_sc.get(sym, 0)})
            seen_sc[sym] = seen_sc.get(sym, 0) + 1

    # "actionable now" — buy signals from the last 7 days, marked against
    # tonight's tag + price so fresh/extended/faded is explicit (the
    # demarcation the alert stream alone doesn't give)
    verdict_by_sym = {}
    vpath = os.path.join(ROOT, "journal", "analyst_verdicts.csv")
    if os.path.exists(vpath):
        vs = pd.read_csv(vpath)
        vs["logged_at"] = pd.to_datetime(vs["logged_at"], errors="coerce")
        # connectivity audit 2026-07-19: only attach RECENT verdicts — a
        # week-old BUY was decorating fresh alerts as if current. 10d covers
        # the 7d actionable window with slack; the verdict date rides along
        # so the human sees exactly how fresh the read is.
        cutoff = pd.Timestamp.now() - pd.Timedelta(days=10)
        for _, v in vs[vs["logged_at"] >= cutoff].iterrows():
            verdict_by_sym[v["symbol"]] = (f"{v['verdict']}/{v.get('conviction', '')}"
                                           f"/{v.get('size', '')} ({v['logged_at']:%d %b})")
    # entry-fidelity labels per buy alert (journal/entry_signals.csv) — shows
    # whether an alert was the exact backtested trigger or a watch-the-pivot
    trigger_by_sym = {}
    espath = os.path.join(ROOT, "journal", "entry_signals.csv")
    if os.path.exists(espath):
        es = pd.read_csv(espath)
        es["logged_at"] = pd.to_datetime(es["logged_at"], errors="coerce")
        for _, r in es[es["logged_at"] >= pd.Timestamp.now() - pd.Timedelta(days=7)].iterrows():
            trigger_by_sym[r["symbol"]] = str(r.get("entry_status", ""))

    actionable = []
    if not journal.empty:
        jj = journal.copy()
        jj["logged_at"] = pd.to_datetime(jj["logged_at"], errors="coerce")
        recent = jj[(jj["kind"].isin(["BUY CANDIDATE", "RE-ENTRY WINDOW"]))
                    & (jj["logged_at"] >= pd.Timestamp.now() - pd.Timedelta(days=7))]
        for _, r in recent.iloc[::-1].iterrows():
            sym = r["symbol"]
            df = load_ohlcv(sym)
            now_px = round(float(df["close"].iloc[-1]), 2) if df is not None and len(df) else None
            alert_px = _num(r.get("close"))
            tag_now = tags.get(sym, "")
            vetoed = str(r.get("vetoed", "")).lower() == "true"
            if vetoed:
                status = "VETOED"
            elif tag_now == "CONFIRMED":
                status = "ACTIONABLE"
            elif tag_now == "EXTENDED":
                status = "RAN AWAY"
            else:
                status = "FADED"
            # conviction: the alert-night number; older journal rows that
            # predate a card fall back to the weekly shortlist score
            conv = _num(r.get("conviction_score"), 0)
            if conv is None and sym in score_by_sym and pd.notna(score_by_sym[sym]):
                conv = round(float(score_by_sym[sym]), 0)
            actionable.append({
                "sym": sym, "d": f"{r['logged_at']:%d %b}", "kind": str(r["kind"]),
                "alert_px": alert_px, "now_px": now_px,
                "chg": round((now_px / alert_px - 1) * 100, 1) if now_px and alert_px else None,
                "conv": conv, "cov": _num(r.get("coverage_pct"), 0), "tag": tag_now,
                "trigger": trigger_by_sym.get(sym, ""),
                "verdict": verdict_by_sym.get(sym, ""), "status": status})

    # one row per SYMBOL: the same name re-alerting across nights showed as
    # duplicate rows (v4 verbosity fix) — keep the newest, count the rest
    # (rows arrive newest-first from the reversed journal iteration)
    seen_syms: dict = {}
    deduped = []
    for a in actionable:
        if a["sym"] in seen_syms:
            seen_syms[a["sym"]]["n"] += 1
            continue
        a["n"] = 1
        seen_syms[a["sym"]] = a
        deduped.append(a)
    actionable = deduped

    # decision-first ordering + a short action label per row; the full
    # explanation lives in a hover tooltip (DOEXPL in the template), not
    # repeated on every row (v4 verbosity fix)
    def _do(a):
        if a["status"] == "VETOED":
            return "DO NOT BUY", "veto"
        if a["status"] == "FADED":
            return "IGNORE", "mute"
        if a["status"] == "RAN AWAY":
            return "WAIT", "warn"
        if a["trigger"] == "VALIDATED":
            return "BUY SETUP", "act"
        if a["trigger"] == "AWAITING TRIGGER":
            return "WATCH", "watch"
        return "WEAK", "weak"
    _srank = {"ACTIONABLE": 0, "RAN AWAY": 1, "FADED": 2, "VETOED": 3}
    _trank = {"VALIDATED": 0, "AWAITING TRIGGER": 1, "NO VCP BASE": 2, "": 3}
    for a in actionable:
        a["do"], a["dokind"] = _do(a)
    actionable.sort(key=lambda a: (_srank.get(a["status"], 9),
                                   _trank.get(a["trigger"], 9),
                                   -(a["conv"] or 0)))

    try:
        paper = paper_summary()
    except Exception:  # noqa: BLE001 — dashboard must build even if paper book breaks
        paper = {}

    tag_counts = pd.Series(list(tags.values())).value_counts().to_dict() if tags else {}
    heat = []
    if not focus.empty:
        g = focus.groupby("industry")["rs_pctile"].agg(["mean", "count"])
        g = g[g["count"] >= 3].sort_values("mean", ascending=False)
        heat = [{"ind": str(i)[:24], "rs": round(float(r["mean"]), 0), "n": int(r["count"])}
                for i, r in g.iterrows()][:18]

    return {
        "generated": datetime.now().strftime("%d %b %Y, %H:%M"),
        "price_date": str(bench["date"].iloc[-1].date()) if bench is not None and len(bench) else "",
        "scan_date": scan_date, "defensive": regime_defensive,
        "health_ok": bench_age <= 5 and len(tags) > 400,
        "funnel": [
            ["NSE index universe", len(universe), "official constituents, refreshed weekly"],
            ["Watched nightly", len(tags), "enough history for a mechanical read"],
            ["Focus list", len(focus), "top relative strength (reporting)"],
            ["Actionable tags", tag_counts.get("CONFIRMED", 0) + tag_counts.get("ANTICIPATION", 0),
             "CONFIRMED + ANTICIPATION today"],
            ["Alerts tonight", len([a for a in alerts if a["kind"] != "POSITION"]),
             "state transitions only"],
        ],
        "tags": tag_counts, "alerts": alerts, "verdicts": verdicts, "ai_picks": ai_picks,
        "radar": radar,
        "rows": screener_rows, "closes": closes, "ohlc": ohlc, "details": details,
        "fund": fund_series, "positions": pos_rows, "journal": j_rows,
        "journal_total": journal_total, "scorecard": score_rows,
        "actionable": actionable, "paper": paper,
        "outcomes": out_stats, "nifty": nifty,
        "heat": heat,
        # sizing matrix v2 (2026-07-12): equity-basis sizing adopted — the old
        # 21.5% figure was a cash-basis measurement artifact. Ideal-fill /
        # stressed pairs shown; stress = next-open fills + gap stops + costs.
        "kpi": {"exp": "+1.67R", "cagr": "47% / 33%", "dd": "-18.5 / -20.7%", "payoff": "9.6:1"},
    }


def build() -> None:
    payload = json.dumps(build_payload(), separators=(",", ":"), default=str)
    html = TEMPLATE.replace("%%PAYLOAD%%", payload)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"dashboard -> {OUT}  ({os.path.getsize(OUT) / 1e6:.1f} MB)")


TEMPLATE = r"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Golden Stock Command Center</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@500&display=swap" rel="stylesheet">
<script src="https://unpkg.com/lightweight-charts@4.2.0/dist/lightweight-charts.standalone.production.js"></script>
<style>
:root{--bg:#0e1116;--panel:#12161d;--card:#151b23;--card2:#1b222d;--line:#232b37;--line2:#303c4c;
--txt:#e6e9ee;--dim:#94a0b0;--faint:#67748b;--grn:#34d399;--red:#f87171;--amb:#fbbf24;--blu:#5aa2ff;--vio:#a78bfa;
--mono:'JetBrains Mono',ui-monospace,Consolas,monospace}
*{box-sizing:border-box;margin:0}
::selection{background:#34d39930}
::-webkit-scrollbar{width:8px;height:8px}
::-webkit-scrollbar-thumb{background:#2b3543;border-radius:8px}
::-webkit-scrollbar-thumb:hover{background:#3a4759}
::-webkit-scrollbar-track{background:transparent}
body{background:var(--bg);color:var(--txt);font-family:Inter,system-ui,sans-serif;display:flex;min-height:100vh}
.mono,td.mono{font-family:var(--mono);font-variant-numeric:tabular-nums;font-size:12px}
nav{width:204px;background:var(--panel);border-right:1px solid var(--line);padding:18px 10px;position:fixed;height:100vh;
z-index:40;display:flex;flex-direction:column}
nav h1{font-size:14.5px;font-weight:700;padding:2px 12px 14px;letter-spacing:-.2px}
nav h1 span{color:var(--grn)}
.navbtn{display:flex;align-items:center;gap:10px;width:100%;padding:8px 12px;border:0;border-radius:8px;
background:transparent;color:var(--dim);font:500 13px Inter;cursor:pointer;margin:1px 0;text-align:left;
transition:background .12s,color .12s}
.navbtn svg{flex:0 0 auto;opacity:.7}
/* desktop sidebar: gap between the search box and the first tab (was an
   inline style, which beat the mobile margin reset and knocked Overview
   out of line with the other tabs on the horizontal bar) */
nav>.navbtn:first-of-type{margin-top:12px}
.navbtn:hover{background:var(--card2);color:var(--txt)}
.navbtn.on{background:var(--card2);color:var(--txt);font-weight:600;box-shadow:inset 2px 0 0 var(--grn)}
.navbtn.on svg{color:var(--grn);opacity:1}
.searchhint{margin:10px 2px 0;padding:7px 12px;border:1px solid var(--line);border-radius:8px;color:var(--faint);
font-size:11.5px;cursor:pointer;display:flex;justify-content:space-between;align-items:center;transition:.15s}
.searchhint:hover{border-color:var(--line2);color:var(--dim)}
.searchhint kbd{font:600 10px var(--mono);border:1px solid var(--line2);border-radius:5px;padding:2px 6px;color:var(--dim);background:var(--card2)}
#runpanel{margin-top:18px;border-top:1px solid var(--line);padding-top:14px}
.runhead{font-size:10px;letter-spacing:1.2px;color:var(--faint);padding:0 12px 8px;font-weight:700}
.runbtn{display:block;width:100%;padding:8px 12px;border:1px solid var(--line);border-radius:8px;
background:transparent;color:var(--dim);font:500 12px Inter;cursor:pointer;margin:4px 0;text-align:left;transition:.15s}
.runbtn:hover{background:var(--card2);color:var(--grn);border-color:var(--line2)}
.runbtn:disabled{opacity:.4;cursor:not-allowed}
.runnote{font-size:10px;color:var(--faint);line-height:1.5;padding:6px 12px 0}
#runstatus{font-size:10.5px;line-height:1.55;padding:8px 6px 0;color:var(--dim)}
#runstatus .runlog{background:var(--bg);border:1px solid var(--line);border-radius:8px;padding:7px 9px;
margin-top:6px;max-height:180px;overflow-y:auto;font:10px/1.5 ui-monospace,Consolas,monospace;
white-space:pre-wrap;word-break:break-all;color:var(--dim)}
@keyframes runpulse{50%{opacity:.45}}
.runlive{color:var(--amb);animation:runpulse 1.2s infinite}
main{margin-left:204px;flex:1;padding:20px 28px 40px;max-width:1280px}
.badge{padding:4px 10px;border-radius:6px;font-size:10.5px;font-weight:600;letter-spacing:.3px}
.b-amb{background:#fbbf2412;color:var(--amb);border:1px solid #fbbf2438}
.b-grn{background:#34d39912;color:var(--grn);border:1px solid #34d39938}
.b-red{background:#f8717112;color:var(--red);border:1px solid #f8717138}
.top{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px;
padding-bottom:12px;margin-bottom:16px;border-bottom:1px solid var(--line)}
.sub{display:none}
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px 18px;margin-bottom:14px}
h2{font-size:11px;font-weight:600;color:var(--dim);text-transform:uppercase;letter-spacing:1.2px;margin-bottom:12px}
.info{display:inline-flex;flex:0 0 16px;width:16px;height:16px;border-radius:50%;
background:var(--card2);border:1px solid var(--line2);color:var(--dim);
font:700 10px/1 Inter;align-items:center;justify-content:center;cursor:help;margin-left:7px;vertical-align:-2px;
text-transform:none;letter-spacing:0;transition:.12s}
.info:hover{color:var(--txt);border-color:var(--dim);background:#232c39}
.tip{position:fixed;display:none;max-width:320px;background:#1e2632;border:1px solid var(--line2);border-radius:8px;
padding:9px 12px;font:400 11.5px/1.6 Inter;color:#c4cdd8;z-index:100;box-shadow:0 10px 32px #0009;pointer-events:none}
.kpis{display:flex;gap:0;margin-bottom:14px;background:var(--card);border:1px solid var(--line);
border-radius:12px;padding:13px 6px;justify-content:space-around}
.kpi{padding:2px 18px;border-left:1px solid var(--line)}
.kpi:first-child{border-left:0}
.kpi b{display:block;font-size:21px;font-weight:700;margin-top:3px;letter-spacing:-.3px}
/* child selector: the nested .info "?" must not inherit the label's
   display:block/uppercase styling (it was dropping onto its own line) */
.kpi>span{color:var(--faint);font-size:9.5px;text-transform:uppercase;letter-spacing:.9px;display:block;white-space:nowrap}
.grid2{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}
.chip{display:inline-flex;gap:7px;align-items:center;border:1px solid;border-radius:7px;
padding:5px 11px;margin:2px 5px 2px 0;font-size:12px;background:transparent;cursor:pointer;transition:.15s}
.chip.off{opacity:.32}
.chip span{color:var(--dim);font-family:var(--mono);font-size:11px}
.alert{display:flex;gap:10px;padding:10px 13px;border-left:2px solid var(--grn);background:var(--card2);
border-radius:0 8px 8px 0;margin:8px 0;font-size:12.8px}
.ak{font-weight:600;color:var(--grn);white-space:nowrap}
.quiet{color:var(--dim);font-size:12.8px;padding:6px 0}
table{width:100%;border-collapse:collapse;font-size:12.6px}
th{color:var(--faint);text-align:left;font-weight:600;font-size:10px;text-transform:uppercase;
letter-spacing:.7px;padding:7px 9px;border-bottom:1px solid var(--line);cursor:pointer;user-select:none;position:sticky;top:0;background:var(--card)}
td{padding:8px 9px;border-bottom:1px solid #1c232e}
tbody tr{cursor:pointer;transition:background .1s}
tbody tr:hover{background:var(--card2)}
.sym{font-weight:600;font-size:12.6px;letter-spacing:.1px}
.dim{color:var(--dim)}.mono{font-family:var(--mono)}
.ndot{display:inline-block;margin-left:5px;padding:1px 5px;border-radius:5px;background:var(--card2);
border:1px solid var(--line2);color:var(--faint);font:600 9.5px var(--mono)}
.pill{border:1px solid;border-radius:5px;padding:2px 7px;font-size:10px;font-weight:600;letter-spacing:.3px}
.convcell{display:inline-flex;align-items:center;gap:7px;white-space:nowrap}
.scorebar{display:inline-block;width:46px;height:5px;background:var(--card2);border-radius:3px;flex:0 0 auto}
.scorebar div{height:5px;border-radius:3px;background:var(--grn)}
td{white-space:nowrap}
td.wrap{white-space:normal}
input,select{background:var(--bg);border:1px solid var(--line);border-radius:8px;color:var(--txt);
padding:7px 12px;font:500 12.5px Inter;outline:0}
input:focus{border-color:var(--dim)}
.fbar2{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:12px}
.heatgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}
.heatcell{border-radius:8px;padding:9px 11px;font-size:11.5px;border:1px solid var(--line)}
.heatcell b{display:block;font-size:15px;font-family:var(--mono)}
.drawer{position:fixed;top:0;right:-720px;width:700px;height:100vh;background:#141a22fa;
border-left:1px solid var(--line2);z-index:50;transition:right .25s cubic-bezier(.2,.8,.2,1);
overflow-y:auto;padding:22px;backdrop-filter:blur(10px)}
.drawer.open{right:0}
.overlay{position:fixed;inset:0;background:#0009;z-index:40;opacity:0;pointer-events:none;transition:.2s}
.overlay.show{opacity:1;pointer-events:auto}
.dclose{float:right;background:var(--card2);border:1px solid var(--line);color:var(--dim);border-radius:8px;
padding:6px 12px;cursor:pointer;font-weight:600}
.minis{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}
.mini{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:13px}
.mini h3{font-size:10px;color:var(--dim);text-transform:uppercase;letter-spacing:.9px;margin-bottom:9px}
.actcard{border-color:#34d3992e}
.funnelline{color:var(--faint);font-size:11px;margin:2px 4px 14px;font-family:var(--mono)}
.funnelline b{color:var(--dim);font-weight:600}
.funnelline .sep{color:var(--line2);padding:0 7px}
.pal{position:fixed;inset:0;background:#0a0d12cc;z-index:80;display:none;backdrop-filter:blur(6px)}
.pal.show{display:flex;align-items:flex-start;justify-content:center;padding-top:12vh}
.palbox{width:580px;max-width:92vw;background:#161c25fa;border:1px solid var(--line2);border-radius:12px;
box-shadow:0 24px 80px #000c;overflow:hidden;animation:palin .15s ease}
@keyframes palin{from{transform:scale(.98) translateY(-5px);opacity:0}}
.palbox input{width:100%;border:0;border-bottom:1px solid var(--line);border-radius:0;background:transparent;
padding:15px 17px;font:500 14.5px Inter;color:var(--txt)}
.pallist{max-height:46vh;overflow-y:auto;padding:6px}
.palrow{display:flex;gap:12px;align-items:center;padding:8px 12px;border-radius:8px;cursor:pointer;font-size:13px}
.palrow.on,.palrow:hover{background:var(--card2)}
.palrow .sym{min-width:104px}
.palrow .pill{margin-left:auto;flex:0 0 auto}
.palempty{padding:18px;color:var(--faint);font-size:13px}
.posrow{display:flex;justify-content:space-between;margin:3px 0;font-size:12.8px}
.track{height:7px;background:var(--card2);border-radius:4px;margin:11px 0 6px;position:relative}
.trackfill{height:7px;border-radius:4px;background:linear-gradient(90deg,var(--red),var(--amb),var(--grn))}
.mbar{display:flex;align-items:center;gap:10px;margin:6px 0}
.mlabel{width:230px;font-size:12px}
.mtrack{flex:1;height:10px;background:var(--card2);border-radius:5px}
.mfill{height:10px;border-radius:5px}
.memo{white-space:pre-wrap;font-size:12.6px;line-height:1.7;color:var(--txt)}
.axis{color:var(--faint);font-size:10px;letter-spacing:.3px}
.legendline{color:var(--dim);font-size:11.5px;line-height:1.6;margin-top:10px;border-top:1px solid var(--line);padding-top:10px}
footer{color:var(--faint);font-size:10.5px;margin-top:24px;line-height:1.7}
.tab{display:none}.tab.on{display:block}
.acthead{font-size:13px;margin-bottom:10px;display:flex;justify-content:space-between;align-items:baseline;flex-wrap:wrap;gap:6px}
.dochip{display:inline-block;padding:2.5px 8px;border-radius:5px;border:1px solid;font-size:10px;font-weight:600;letter-spacing:.4px;white-space:nowrap}
details.actrest{margin-top:8px}
details.actrest summary{cursor:pointer;color:var(--dim);font-size:12px;padding:6px 0;list-style-position:outside}
details.actrest summary:hover{color:var(--txt)}
details.actrest table{opacity:.8}
@media(max-width:1000px){
body{flex-direction:column}
nav{position:sticky;top:0;width:100%;height:auto;display:flex;flex-direction:row;align-items:center;gap:2px;
padding:10px 12px;overflow-x:auto;border-right:0;border-bottom:1px solid var(--line);
scrollbar-width:none;background:var(--panel)}
nav::-webkit-scrollbar{display:none}
nav h1{padding:0 12px 0 2px;white-space:nowrap}
.navbtn{width:auto;white-space:nowrap;padding:8px 11px;margin:0;flex:0 0 auto}
nav>.navbtn:first-of-type{margin-top:0}
.navbtn.on{box-shadow:inset 0 -2px 0 var(--grn)}
#runpanel{display:none!important}
main{margin:0;padding:14px;max-width:100%}.grid2{grid-template-columns:1fr}
.kpis{flex-wrap:wrap;gap:8px}.kpi{border-left:0;padding:2px 10px}
.searchhint{display:none}.drawer{width:100vw;right:-100vw}
/* wide tables scroll inside their card instead of clipping at the edge */
.card{overflow-x:auto}
.badge{white-space:nowrap}
.top{align-items:flex-start}}
@media(max-width:640px){
main{padding:10px}
.card{padding:12px 12px;border-radius:10px}
table{font-size:11.5px}
th{font-size:9px}
.minis{grid-template-columns:1fr}
.kpi b{font-size:16px}
.acthead{font-size:12px}
.dochip{font-size:9px;padding:2px 6px}
.drawer{padding:16px 14px}
.funnelline{font-size:10.5px;line-height:1.8}}
</style></head><body>
<nav><h1>Golden<span>Stock</span></h1>
<div class="searchhint" onclick="openPalette()"><span>Search stocks&hellip;</span><kbd>Ctrl K</kbd></div>
<button class="navbtn on" data-t="overview"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg> Overview</button>
<button class="navbtn" data-t="picks"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9z"/><path d="M18.5 15.5l.7 1.8 1.8.7-1.8.7-.7 1.8-.7-1.8-1.8-.7 1.8-.7z"/></svg> AI Picks</button>
<button class="navbtn" data-t="screener"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M4 6h16M7 12h10M10 18h4"/></svg> Screener</button>
<button class="navbtn" data-t="positions"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 012-2h4a2 2 0 012 2v2"/></svg> Positions</button>
<button class="navbtn" data-t="journal"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6M9 16h3"/></svg> Journal</button>
<div id="runpanel" style="display:none">
  <div class="runhead">RUN (local server)</div>
  <button class="runbtn" data-job="daily" title="scan + paper book + outcomes + dashboard — no AI, no credits">&#8635; Daily scan (no AI)</button>
  <button class="runbtn" data-job="daily_ai" title="adds the sonnet analyst, max 3 deep-dives — moderate credits">&#8635; Scan + AI analyst</button>
  <button class="runbtn" data-job="weekly" title="full weekly refresh, AI committee SKIPPED — no Opus credits">&#8635; Weekly refresh (no AI)</button>
  <div class="runnote">AI committee runs only from the scheduled weekly job &mdash; never from here (credit guard).</div>
  <div id="runstatus"></div>
</div>
</nav>
<main>
<div class="top"><div id="badges"></div><div class="dim" style="font-size:12px" id="gen"></div></div>
<div class="sub">Alerts fire on state transitions only &middot; entries are technical-only (evidence-locked) &middot; click any stock for the full picture</div>

<div class="tab on" id="overview">
  <div class="card actcard"><h2 style="color:var(--grn)">Actionable now &mdash; buy signals, last 7 days<span class="info" data-tip="The only panel you act from. BUY SETUP = the exact backtested trigger fired (pivot break on ≥1.5× volume) — open the drawer for the sized plan. WATCH = VCP base ready, breakout not confirmed yet. WEAK = uptrend without the proven trigger. Resolved rows (ran away / faded / vetoed) need nothing — a faded signal is the system saving you from a stale entry.">?</span></h2>
    <div id="actionable"></div></div>
  <div class="card" id="radarcard" style="display:none"><h2 style="color:#a78bfa">News radar &mdash; material filings<span class="info" data-tip="News-FIRST discovery: every NSE filing since the last scan, whitelist-classified (order wins, M&A, approvals / probes, pledges, exits / fund raises), matched to the universe and cross-referenced with tonight's technical state. CONFLUENCE = positive news on a chart the technical layer already rates CONFIRMED/ANTICIPATION — the names to research first. News moves attention, never entries — trades stay technical.">?</span></h2>
    <div id="radarbody"></div></div>
  <div class="kpis" id="kpis"></div>
  <div class="funnelline" id="funnel"></div>
  <div class="grid2"><div>
    <div class="card"><h2>Tonight</h2><div id="alerts"></div>
    <div id="verdictcard" style="display:none;margin-top:14px"><h2>AI analyst verdicts</h2><div class="memo" id="verdicts"></div></div></div>
    <div class="card"><h2>NIFTY 50 &middot; regime line (150-DMA)</h2><div id="niftychart" style="height:190px"></div></div>
  </div><div>
    <div class="card"><h2>Tag board<span class="info" data-tip="CONFIRMED = passes all 8 uptrend checks — a monitored pool, not a buy list; you act only on fresh transitions and top conviction, sized by the plan in each stock's drawer. ANTICIPATION = base forming, watch with zero capital.">?</span></h2><div id="tagboard"></div></div>
    <div class="card"><h2>Sector heat &mdash; avg RS percentile</h2><div class="heatgrid" id="heat"></div></div>
  </div></div>
</div>

<div class="tab" id="picks">
  <div class="card" style="padding:12px 18px"><h2 style="margin:0">AI investment committee<span class="info" data-tip="Claude reads the whole mechanically-scored shortlist (dimensions, conviction, sector, RS), selects the optimum 3-5, deep-researches each on the web, and writes the investment case. The machine qualifies & scores; the AI curates & explains. Entry/stop/size stay mechanical. Picks are journaled and measured vs the mechanical top-N over time.">?</span></h2></div>
  <div id="picksbody"></div>
</div>

<div class="tab" id="screener">
  <div class="card">
    <div class="fbar2">
      <input id="q" placeholder="search symbol / company..." style="width:200px">
      <select id="find"><option value="">all industries</option></select>
      <span id="tierfilters"></span>
      <span style="width:1px;height:22px;background:var(--line);margin:0 4px"></span>
      <span id="tagfilters"></span>
      <span class="info" data-tip="Cap tiers: Micro < ₹2k Cr (highest multibagger runway, highest risk) · Small ₹2–12k Cr · Mid ₹12–50k Cr · Large > ₹50k Cr. Filter Micro + CONFIRMED for the potential-multibagger view.">?</span>
      <span class="dim" style="font-size:12px;margin-left:auto" id="count"></span>
    </div>
    <div style="max-height:66vh;overflow:auto">
    <table id="tbl"><thead><tr>
      <th data-k="sym">Symbol</th><th data-k="tier">Cap</th><th data-k="ind">Industry</th><th data-k="tag">Tag</th>
      <th data-k="rs">RS%</th><th data-k="score">Conviction</th><th data-k="arch">Archetype</th>
      <th data-k="roce">ROCE</th><th data-k="pe">P/E</th><th data-k="pgttm">PAT TTM%</th>
      <th data-k="close">Price</th><th>120d</th></tr></thead><tbody></tbody></table></div>
  </div>
</div>

<div class="tab" id="positions">
  <div class="card" style="border-color:#a78bfa3a"><h2 style="color:var(--vio)">Paper book &mdash; every analyst BUY, traded on paper<span class="info" data-tip="Each analyst BUY verdict is auto-entered at the NEXT session's open, sized by the mechanical plan (FULL/HALF respected, regime-scaled, ₹10L notional book), and exited by the same two-lot rules as real positions. Nothing is discretionary — this is the running audit of whether the analyst layer makes money.">?</span></h2>
  <div class="kpis" id="paperkpi" style="margin-bottom:12px"></div>
  <div id="paperbody"></div></div>
  <div id="poswrap"></div>
</div>

<div class="tab" id="journal">
  <div class="kpis" id="jstats"></div>
  <div class="card"><h2>Buy-signal scorecard &mdash; every buy alert, marked to market<span class="info" data-tip="One row per BUY CANDIDATE / RE-ENTRY alert the machine ever fired, scored against its own suggested stop. R = profit in units of initial risk (+2R = made twice what the stop risked). Max R = best excursion so far. stopped = hit the stop (-1R, closed). This table only ever grows — signals never disappear, whatever happens to tags later.">?</span></h2>
  <div style="max-height:44vh;overflow:auto">
  <table><thead><tr><th>When</th><th>Symbol</th><th>Type</th><th>Conv</th><th>Alert &#8377;</th><th>Stop</th>
  <th>Ret %</th><th>R now</th><th>Max R</th><th>Status</th></tr></thead>
  <tbody id="scorebody"></tbody></table></div></div>
  <div class="card"><h2>All tag events (last 50) &mdash; the raw stream</h2>
  <table><thead><tr><th>When</th><th>Symbol</th><th>Signal</th><th>Detail</th></tr></thead>
  <tbody id="jbody"></tbody></table></div>
</div>

<div class="overlay" id="ovl" onclick="closeDrawer()"></div>
<div class="pal" id="pal"><div class="palbox">
<input id="palq" placeholder="Search stocks — symbol or company&hellip;" autocomplete="off">
<div class="pallist" id="pallist"></div></div></div>
<div class="drawer" id="drawer"></div>
<footer>Data: NSE constituents &middot; Yahoo OHLCV (verified vs Zerodha) &middot; screener.in public pages &middot; NSE announcements RSS &middot; Google News. Decision support only &mdash; not investment advice.</footer>
</main>
<script>
const D=%%PAYLOAD%%;
const TC={CONFIRMED:'#34d399',ANTICIPATION:'#5aa2ff',EXTENDED:'#fbbf24',BROKEN:'#f87171',WATCH:'#64748b'};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/</g,'&lt;');

/* tooltip engine — hover on desktop, tap-to-toggle on .info icons (touch).
   All explanatory prose lives here instead of permanently on screen (v4). */
const tipEl=document.createElement('div');tipEl.className='tip';document.body.appendChild(tipEl);
let tipPin=null;
function showTip(el){const t=el.dataset.tip;if(!t)return;
 tipEl.textContent=t;tipEl.style.display='block';
 const r=el.getBoundingClientRect();
 tipEl.style.left=Math.min(Math.max(8,r.left+r.width/2-tipEl.offsetWidth/2),innerWidth-tipEl.offsetWidth-8)+'px';
 tipEl.style.top=(r.bottom+8+tipEl.offsetHeight>innerHeight?r.top-tipEl.offsetHeight-8:r.bottom+8)+'px';}
function hideTip(){tipEl.style.display='none';tipPin=null;}
document.addEventListener('mouseover',e=>{if(tipPin)return;
 const el=e.target.closest('[data-tip]');el?showTip(el):hideTip();});
document.addEventListener('click',e=>{const el=e.target.closest('.info[data-tip]');
 if(el){e.stopPropagation();e.preventDefault();
  if(tipPin===el)hideTip();else{showTip(el);tipPin=el;}return;}
 if(tipPin)hideTip();},true);

/* nav */
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>{
 document.querySelectorAll('.navbtn').forEach(x=>x.classList.remove('on'));
 document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));
 b.classList.add('on');$('#'+b.dataset.t).classList.add('on');
 if(b.dataset.t==='positions'&&!window._pos)drawPositions();
 if(b.dataset.t==='picks'&&!window._picks)drawPicks();});

/* header */
/* next scheduled cloud scan: Mon-Fri 13:05 UTC (+ GitHub cron delay) */
function nextScanText(){const now=new Date();let d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate(),13,5));
 while(d<=now||d.getUTCDay()===0||d.getUTCDay()===6)d=new Date(d.getTime()+864e5),d.setUTCHours(13,5,0,0);
 const h=Math.round((d-now)/36e5);
 return' · next scan '+d.toLocaleDateString(undefined,{weekday:'short'})+' ~'+d.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})+' ('+(h<=24?'in ~'+h+'h':d.toLocaleDateString())+')'}
$('#gen').textContent='generated '+D.generated+' · last scan '+D.scan_date+' · prices as of '+D.price_date+nextScanText();
$('#badges').innerHTML=(D.defensive?'<span class="badge b-amb">DEFENSIVE — HALF SIZE (NIFTY &lt; 150-DMA)</span>':'<span class="badge b-grn">NORMAL RISK</span>')+' '+(D.health_ok?'<span class="badge b-grn">HEALTH OK</span>':'<span class="badge b-red">HEALTH FAILED</span>');

/* KPIs — number + label; the caveat rides in a tooltip, not on screen (v4) */
$('#kpis').innerHTML=[['Expectancy / trade',D.kpi.exp,'Validated 3y window, after costs. Changing the rules requires new pre-registered evidence.'],
['CAGR ideal / stressed',D.kpi.cagr,'Survivor-biased, so directional. Stressed = next-open fills + gap-aware stops + full costs — the honest planning number.'],
['Max drawdown',D.kpi.dd,'Ideal / stressed. Portfolio circuit breaker pauses everything at -25%.'],
['Payoff ratio',D.kpi.payoff,'Average win : average loss. The edge is few big winners paying for many small stops (~30% win rate by design).']]
.map(k=>`<div class="kpi"><span>${k[0]}<span class="info" data-tip="${esc(k[2])}">?</span></span><b>${k[1]}</b></div>`).join('');

/* funnel — one-line breadcrumb (context, not a decision surface) */
$('#funnel').innerHTML=D.funnel.map(f=>`<span title="${esc(f[2])}"><b>${f[1]}</b> ${esc(f[0].toLowerCase())}</span>`).join('<span class="sep">&rsaquo;</span>');

/* alerts */
$('#alerts').innerHTML=D.alerts.length?D.alerts.map(a=>`<div class="alert"><span class="ak">${esc(a.kind)}</span><span>${esc(a.text)}</span></div>`).join(''):'<div class="quiet">No transitions tonight — silence is the system working.</div>';
if(D.verdicts){$('#verdictcard').style.display='block';$('#verdicts').textContent=D.verdicts;}

/* actionable now — v4: one row per symbol (×N = re-alerts), BUY SETUP +
   WATCH rows on top, WEAK and resolved folded behind toggles; each action
   chip explains itself on hover (DOEXPL) instead of per-row prose */
const DOC={act:'#34d399',watch:'#fbbf24',weak:'#94a3b8',warn:'#fbbf24',mute:'#64748b',veto:'#f87171'};
const DOEXPL={
 act:'Exact backtested trigger fired — pivot break on ≥1.5× volume. Open the drawer for the sized two-lot plan.',
 watch:'VCP base ready — buy only if price breaks the pivot on ≥1.5× volume. No entry yet.',
 weak:'Uptrend (CONFIRMED tag) but no VCP base/breakout — the validated edge is not established for this entry.',
 warn:'Ran away: price extended after the alert — do not chase; a re-entry alert fires if it cools into a new setup.',
 mute:'The setup faded after the alert (tag no longer CONFIRMED) — a stale entry the system saved you from.',
 veto:'Hard governance/leverage veto — do not buy regardless of technicals.'};
(function(){
const all=D.actionable||[];
if(!all.length){$('#actionable').innerHTML='<div class="quiet">No buy signals in the last 7 days.</div>';return;}
const live=all.filter(a=>a.status==='ACTIONABLE'),rest=all.filter(a=>a.status!=='ACTIONABLE');
const prime=live.filter(a=>a.dokind==='act'||a.dokind==='watch'),weak=live.filter(a=>a.dokind==='weak');
const nv=prime.filter(a=>a.dokind==='act').length;
const row=a=>{const c=DOC[a.dokind]||'#94a3b8';
 return `<tr onclick="openDrawer('${a.sym}')">
 <td><span class="dochip" data-tip="${esc(DOEXPL[a.dokind]||'')}" style="background:${c}12;color:${c};border-color:${c}45">${a.do}</span></td>
 <td class="sym">${a.sym}${a.n>1?`<span class="ndot" title="alerted ${a.n}× in 7 days">×${a.n}</span>`:''}</td>
 <td class="mono">${a.conv==null?'—':(a.cov!=null&&a.cov<60?`<span data-tip="Technical read — only ${a.cov}% of the 8 scored questions had data (fundamentals unavailable at alert time). Not comparable with full-coverage conviction scores.">${a.conv}<span style="color:#fbbf24">°</span></span>`:a.conv)}</td>
 <td class="dim" style="font-size:11.5px">${a.verdict?esc(a.verdict):'—'}</td>
 <td class="mono">${a.alert_px??''} &rarr; ${a.now_px??''} <span style="color:${a.chg>0?'#34d399':a.chg<0?'#f87171':'#64748b'}">${a.chg!=null?(a.chg>0?'+':'')+a.chg+'%':''}</span></td>
 <td class="dim mono">${a.d}</td></tr>`};
const hdr='<tr><th>Action</th><th>Symbol</th><th>Conv</th><th>Analyst</th><th>Alert &rarr; now</th><th>Alerted</th></tr>';
let h=`<div class="acthead">${nv
 ?`<b style="color:#34d399">&#9679; ${nv} validated buy trigger${nv>1?'s':''} — act today</b>`
 :`<b style="color:#94a3b8">&#9675; No validated triggers — nothing requires action.</b>`}
 <span class="dim" style="font-size:11.5px">${prime.length-nv} awaiting pivot &middot; ${weak.length} weak &middot; ${rest.length} resolved</span></div>`;
if(prime.length)h+=`<table><thead>${hdr}</thead><tbody>`+prime.map(row).join('')+'</tbody></table>';
else h+=`<div class="quiet">No validated or pivot-ready setups right now${weak.length?' — weak-trend signals folded below':''}.</div>`;
if(weak.length)h+=`<details class="actrest"><summary>${weak.length} weak signal${weak.length>1?'s':''} — uptrend, no proven trigger</summary>
<table><thead>${hdr}</thead><tbody>`+weak.map(row).join('')+'</tbody></table></details>';
if(rest.length)h+=`<details class="actrest"><summary>${rest.length} resolved — ran away / faded / vetoed (no action)</summary>
<table><thead>${hdr}</thead><tbody>`+rest.map(row).join('')+'</tbody></table></details>';
$('#actionable').innerHTML=h;})();

/* news radar — news-first discovery panel */
(function(){
const R=D.radar||{};const hits=R.hits||[];
if(!hits.length)return;   // silence is the default — card stays hidden
$('#radarcard').style.display='block';
const CC={pos:'#34d399',neg:'#f87171',attn:'#fbbf24'};
const DOT={pos:'▲',neg:'▼',attn:'◆'};
const shown=hits.slice(0,15);
$('#radarbody').innerHTML=`<table><thead><tr><th></th><th>Symbol</th><th>Tag</th><th>RS%</th><th>Event</th><th>Filing</th></tr></thead><tbody>`+
shown.map(h=>{const c=CC[h.cls]||'#94a3b8';
const badge=h.urgent?'<span class="pill" style="border-color:#f87171;color:#f87171;font-size:9px">HELD</span> ':
 h.confluence?'<span class="pill" style="border-color:#34d399;color:#34d399;font-size:9px" data-tip="Positive news + a chart the technical layer already rates actionable/forming — research first.">CONFLUENCE</span> ':'';
return `<tr onclick="openDrawer('${h.sym}')"${h.confluence?' style="background:#34d39908"':h.urgent?' style="background:#f8717108"':''}>
<td style="color:${c};font-weight:700">${DOT[h.cls]||'•'}</td>
<td class="sym">${h.sym}${h.n>1?`<span class="ndot" title="${h.n} filings">×${h.n}</span>`:''}</td>
<td><span class="pill" style="border-color:${TC[h.tag]||'#475569'};color:${TC[h.tag]||'#94a3b8'}">${esc(h.tag||'—')}</span></td>
<td class="mono">${h.rs!=null?Math.round(h.rs):'—'}</td>
<td style="color:${c};font-size:11.5px">${esc(h.event)} ${badge}</td>
<td class="dim wrap" style="font-size:11px;max-width:420px">${esc(h.subject.replace(/has informed the Exchange (regarding|about|that)?/i,'—').slice(0,120))}</td></tr>`}).join('')+
'</tbody></table>'+(hits.length>15?`<div class="axis" style="margin-top:6px">${hits.length-15} more hits in state/news_radar.json</div>`:'')+
`<div class="axis" style="margin-top:6px">since ${esc((R.window_start||'').slice(0,16).replace('T',' '))} · news moves attention, never entries</div>`;
})();

/* tag board */
$('#tagboard').innerHTML=Object.entries(D.tags).sort((a,b)=>b[1]-a[1]).map(([t,c])=>`<div class="chip" style="border-color:${TC[t]||'#475569'}"><b style="color:${TC[t]||'#94a3b8'}">${t}</b><span>${c}</span></div>`).join('');

/* heat */
$('#heat').innerHTML=D.heat.map(h=>{const g=h.rs>=60?'#34d399':h.rs>=45?'#fbbf24':'#f87171';
return `<div class="heatcell" style="background:${g}14;border-color:${g}33"><b style="color:${g}">${h.rs}</b>${esc(h.ind)}<span class="dim"> · ${h.n}</span></div>`}).join('');

/* sparkline svg */
function spark(a,w=96,h=26){if(!a||a.length<2)return'';const lo=Math.min(...a),hi=Math.max(...a),r=(hi-lo)||1;
const p=a.map((v,i)=>`${(i*w/(a.length-1)).toFixed(1)},${(h-2-(v-lo)/r*(h-5)).toFixed(1)}`).join(' ');
const c=a[a.length-1]>=a[0]?'#34d399':'#f87171';
return `<svg width="${w}" height="${h}"><polyline fill="none" stroke="${c}" stroke-width="1.5" points="${p}"/></svg>`}

/* screener table */
const TIERC={Micro:'#9ec5f4',Small:'#6da7ec',Mid:'#3f87e8',Large:'#64748b'};
let rows=D.rows.slice(),sortK='score',sortA=false,activeTags=new Set(Object.keys(TC));
let activeTiers=new Set(['Micro','Small','Mid','Large','']);
const inds=[...new Set(D.rows.map(r=>r.ind))].sort();
$('#find').innerHTML+=inds.map(i=>`<option>${esc(i)}</option>`).join('');
$('#tierfilters').innerHTML=['Micro','Small','Mid','Large'].map(t=>`<span class="chip" data-tier="${t}" style="border-color:${TIERC[t]}"><b style="color:${TIERC[t]}">${t}</b></span>`).join('')
+`<span class="chip off" data-focus style="border-color:#7c8db0" title="show only the ~320-name RS focus list (reporting view); off = full watched universe"><b style="color:#94a3b8">Focus only</b></span>`;
let focusOnly=false;
document.querySelector('[data-focus]').onclick=e=>{focusOnly=!focusOnly;e.currentTarget.classList.toggle('off',!focusOnly);render();};
$('#tagfilters').innerHTML=Object.keys(TC).map(t=>`<span class="chip" data-tag="${t}" style="border-color:${TC[t]}"><b style="color:${TC[t]}">${t}</b></span>`).join('');
document.querySelectorAll('[data-tag]').forEach(c=>c.onclick=()=>{const t=c.dataset.tag;
activeTags.has(t)?(activeTags.delete(t),c.classList.add('off')):(activeTags.add(t),c.classList.remove('off'));render();});
document.querySelectorAll('[data-tier]').forEach(c=>c.onclick=()=>{const t=c.dataset.tier;
activeTiers.has(t)?(activeTiers.delete(t),c.classList.add('off')):(activeTiers.add(t),c.classList.remove('off'));render();});
$('#q').oninput=render;$('#find').onchange=render;
document.querySelectorAll('#tbl th[data-k]').forEach(th=>th.onclick=()=>{const k=th.dataset.k;
sortA=(sortK===k)?!sortA:false;sortK=k;render();});
function fmtCr(v){if(v==null)return'';return v>=1000?'₹'+(v/1000).toFixed(1)+'k Cr':'₹'+Math.round(v)+' Cr';}
function render(){const q=$('#q').value.toUpperCase(),ind=$('#find').value;
let out=rows.filter(r=>activeTags.has(r.tag)&&activeTiers.has(r.tier)&&(!focusOnly||r.focus)&&(!ind||r.ind===ind)&&(r.sym.includes(q)||r.company.toUpperCase().includes(q)));
out.sort((a,b)=>{let x=a[sortK],y=b[sortK];if(x==null)return 1;if(y==null)return -1;
if(typeof x==='string')return sortA?x.localeCompare(y):y.localeCompare(x);return sortA?x-y:y-x;});
$('#count').textContent=out.length+' stocks';
$('#tbl tbody').innerHTML=out.map(r=>`<tr onclick="openDrawer('${r.sym}')">
<td class="sym">${r.sym}${r.veto?' <span style="color:#f87171">⛔</span>':''}</td>
<td><span class="pill" style="border-color:${TIERC[r.tier]||'#475569'};color:${TIERC[r.tier]||'#94a3b8'}" title="${fmtCr(r.mcap)}">${r.tier||'—'}</span></td>
<td class="dim">${esc(r.ind)}</td>
<td><span class="pill" style="border-color:${TC[r.tag]};color:${TC[r.tag]}">${r.tag||''}</span></td>
<td class="mono">${r.rs??''}</td>
<td>${r.score!=null?`<span class="convcell"><span class="scorebar"><div style="width:${r.score}%"></div></span><b class="mono">${r.score}</b></span>`:'<span class="dim">—</span>'}</td>
<td class="dim wrap">${esc(r.arch)}</td><td class="mono">${r.roce??''}</td><td class="mono">${r.pe??''}</td>
<td class="mono" style="color:${r.pgttm>0?'#34d399':r.pgttm<0?'#f87171':''}">${r.pgttm??''}</td>
<td class="mono">${r.close??''}</td><td>${spark(D.closes[r.sym])}</td></tr>`).join('');}
render();

/* chart factory */
function mkChart(el,h){return LightweightCharts.createChart(el,{height:h,layout:{background:{type:'solid',color:'transparent'},textColor:'#94a0b0',fontFamily:'Inter'},grid:{vertLines:{color:'#1c232e'},horzLines:{color:'#1c232e'}},rightPriceScale:{borderColor:'#232b37'},timeScale:{borderColor:'#232b37'},crosshair:{mode:1}});}
function sma(data,n){const o=[];for(let i=n-1;i<data.length;i++){let s=0;for(let j=i-n+1;j<=i;j++)s+=data[j][4];o.push({time:data[i][0],value:+(s/n).toFixed(2)});}return o;}

/* nifty overview chart */
(function(){const el=$('#niftychart');if(!D.nifty.length)return;const c=mkChart(el,190);
const line=c.addAreaSeries({lineColor:'#5aa2ff',topColor:'#5aa2ff22',bottomColor:'transparent',lineWidth:2});
line.setData(D.nifty.map(p=>({time:p[0],value:p[1]})));
const s=c.addLineSeries({color:'#fbbf24',lineWidth:1,lineStyle:2});
s.setData(D.nifty.filter(p=>p[2]).map(p=>({time:p[0],value:p[2]})));c.timeScale().fitContent();})();

/* drawer */
const DN={rs_and_stage:'Technicals — RS &amp; stage',earnings_inflection:'Earnings inflection',
theme_tailwind:'Theme tailwind (news)',smart_money:'Smart money (FII/DII)',
financial_strength_trend:'Balance-sheet strength',catalyst:'Catalysts (news+filings)',
governance:'Governance',valuation_sanity:'Valuation sanity'};
function fmtNum(v){if(v==null)return'';const a=Math.abs(v);return a>=1000?(v/1000).toFixed(1)+'k':(''+Math.round(v*10)/10);}
function miniBars(labels,vals){if(!vals||!vals.filter(v=>v!=null).length)return'<span class="dim">no data</span>';
const mx=Math.max(...vals.map(v=>Math.abs(v??0)))||1;const mn=Math.min(...vals.map(v=>v??0));
const bars=vals.map((v,i)=>{const hh=Math.abs(v??0)/mx*54+3;
return `<div title="${labels[i]}: ${v}" style="flex:1;height:${hh}px;border-radius:3px;background:${(v??0)>=0?'#34d399':'#f87171'};opacity:.85"></div>`}).join('');
return `<div style="display:flex;justify-content:space-between" class="axis"><span>peak ${fmtNum(mx)}</span>${mn<0?`<span style="color:#f87171">low ${fmtNum(mn)}</span>`:''}</div>
<div style="display:flex;align-items:flex-end;gap:3px;height:62px">${bars}</div>
<div style="display:flex;justify-content:space-between" class="axis"><span>${esc(labels[0]||'')}</span><span>${esc(labels[labels.length-1]||'')}</span></div>`;}
function miniLine(vals,color,caption,labels){if(!vals||vals.filter(v=>v!=null).length<2)return'';
const a=vals.map(v=>v??0);const lo=Math.min(...a),hi=Math.max(...a),r=(hi-lo)||1;
const p=a.map((v,i)=>`${(i*150/(a.length-1)).toFixed(1)},${(44-4-(v-lo)/r*36).toFixed(1)}`).join(' ');
const last=a[a.length-1];
return `<div style="display:flex;align-items:center;gap:10px;margin:4px 0">
<span class="axis" style="width:78px">${caption}</span>
<svg width="150" height="44"><polyline fill="none" stroke="${color}" stroke-width="2" points="${p}"/></svg>
<div style="font-family:var(--mono);font-size:12px"><b style="color:${color}">${fmtNum(last)}</b>
<div class="axis">${fmtNum(lo)}–${fmtNum(hi)}</div></div></div>
<div class="axis" style="margin-left:88px">${esc((labels&&labels[0])||'')} → ${esc((labels&&labels[labels.length-1])||'')}</div>`;}
function whySection(sym){const dt=D.details[sym];
if(!dt)return'<div class="mini" style="margin-top:14px"><h3>Why no score breakdown?</h3><div style="font-size:12.5px" class="dim">Full 8-question scoring runs on the actionable shortlist (CONFIRMED + ANTICIPATION). This stock is currently outside it — it re-enters scoring the moment its tag turns actionable.</div></div>';
let h='<div class="mini" style="margin-top:14px"><h3>Why this score — 8 weighted questions</h3>';
(dt.dims||[]).slice().sort((a,b)=>b.w-a.w).forEach(m=>{
const pct=m.s!=null?Math.round(m.s*100):0;
const col=m.s==null?'#334155':m.s>=.7?'#34d399':m.s>=.4?'#fbbf24':'#f87171';
h+=`<div style="margin:9px 0"><div style="display:flex;justify-content:space-between;font-size:12px">
<span>${DN[m.k]||m.k} <span class="axis">w${m.w}</span></span>
<b class="mono" style="color:${col}">${m.s==null?'no data':pct}</b></div>
<div class="mtrack" style="height:7px;margin:4px 0"><div class="mfill" style="height:7px;width:${m.s==null?0:pct}%;background:${col}"></div></div>
<div class="axis" style="line-height:1.5">${esc(m.n||'')}</div></div>`;});
if((dt.reasons||[]).length)h+=`<div style="margin-top:10px;font-size:12px"><span class="axis">MECHANICAL READ</span><br>${dt.reasons.map(x=>'· '+esc(x)).join('<br>')}</div>`;
h+='</div>';return h;}
function planSection(sym,r){const dt=D.details[sym];if(!dt)return'';
if(r.veto)return`<div class="mini" style="border-color:#f8717155;margin-top:14px"><h3 style="color:#f87171">Vetoed — do not buy</h3><div style="font-size:12.5px">${esc((dt.veto_reasons||[]).join('; '))}</div></div>`;
if(r.tag==='ANTICIPATION')return`<div class="mini" style="border-color:#5aa2ff44;margin-top:14px"><h3 style="color:#5aa2ff">Watch only — zero capital</h3><div style="font-size:12.5px">Stage-1 base forming. Validated as an alert tier only (+0.41R) — capital waits for the confirmed breakout (+1.27R economics). Horizon if it triggers later: weeks–months (trading lot), months–years (core lot).</div></div>`;
const p=dt.plan;
if(!p||!p.shares_total)return r.tag==='CONFIRMED'?`<div class="mini" style="border-color:#f8717144;margin-top:14px"><h3 style="color:#f87171">No mechanical entry plan</h3><div style="font-size:12.5px">The risk engine skips this name: its ATR-based stop would exceed the 12% hard cap — untradeably volatile to size cleanly (Design Law #7). Watch only, not a buy.</div></div>`:'';
return`<div class="mini" style="border-color:#34d39944;margin-top:14px"><h3 style="color:#34d399">If you take this trade (plan, not advice)</h3>
<table style="font-size:12.5px"><tr><td class="dim">Buy</td><td class="mono"><b>${p.shares_total} shares</b> ≈ ₹${fmtNum(p.position_value)} ${p.risk_scale<1?'<span style="color:#fbbf24">(HALF SIZE — defensive regime)</span>':''}</td></tr>
<tr><td class="dim">Entry ~</td><td class="mono">${p.entry_price}</td></tr>
<tr><td class="dim">Stop</td><td class="mono" style="color:#f87171">${p.stop_loss_price} (risk ₹${fmtNum(p.capital_at_risk)} ≈ ${p.risk_scale<1?'0.6':'1.25'}% of capital)</td></tr>
<tr><td class="dim">Breakeven at</td><td class="mono" style="color:#fbbf24">${p.breakeven_trigger} — then stop moves to entry</td></tr>
<tr><td class="dim">Partial at</td><td class="mono" style="color:#34d399">${p.partial_price} — sell ⅓ of trading lot (${p.shares_trading_lot} sh lot)</td></tr>
<tr><td class="dim">Core lot</td><td class="mono">${p.shares_core_lot} sh — exits only on weekly close &lt; 30-week MA</td></tr>
<tr><td class="dim">Horizon</td><td>trading lot: weeks–months · core lot: months–years (the multibagger seat)</td></tr></table></div>`;}
function newsSection(sym){const dt=D.details[sym];if(!dt||!dt.news)return'';const n=dt.news;
const sc=n.sentiment>0.15?'#34d399':n.sentiment<-0.15?'#f87171':'#94a0b0';
const sl=n.sentiment>0.15?'positive':n.sentiment<-0.15?'negative':'neutral';
let h=`<div class="mini" style="margin-top:14px"><h3>News &amp; filings (30d)</h3>
<div style="font-size:12px;margin-bottom:8px" class="dim">
<b style="color:var(--txt)">${n.trusted}</b> trusted-source headlines (of ${n.count} found) ·
sentiment <b style="color:${sc}">${sl}</b> (${n.sent_pos}+ / ${n.sent_neg}-)
${n.themes.length?' · themes: <b style="color:#34d399">'+esc(n.themes.join(', '))+'</b>':''}
${n.events.length?' · events: <b style="color:#5aa2ff">'+esc(n.events.join(', '))+'</b>':''}
<div class="axis" style="margin-top:3px">only trusted sources feed the score; others shown but excluded</div></div>`;
(n.red_flags||[]).forEach(f=>h+=`<div style="color:#f87171;font-size:12px;margin:4px 0">!! ${esc(f)}</div>`);
(n.filings||[]).forEach(f=>h+=`<div style="font-size:12px;margin:4px 0"><span class="pill" style="border-color:#a78bfa;color:#a78bfa">NSE</span> <span class="dim">${f.d}</span> ${esc(f.t)}</div>`);
(n.headlines||[]).forEach(x=>{const dot=x.sn>0?'<span style="color:#34d399">▲</span>':x.sn<0?'<span style="color:#f87171">▼</span>':'<span class="dim">•</span>';
h+=`<div style="font-size:12px;margin:4px 0${x.ru?';opacity:.55':''}">${dot} <span class="dim">${x.d}</span> ${esc(x.t)} <span class="axis">(${esc(x.s)}${x.tr?'':' — unverified'}${x.ru?' — market roundup, excluded from score':''})</span></div>`;});
return h+'</div>';}
window.openDrawer=function(sym){const d=$('#drawer');const r=D.rows.find(x=>x.sym===sym)||{};
const f=D.fund[sym]||{};const hasOhlc=(D.ohlc[sym]||[]).length>10;
d.innerHTML=`<button class="dclose" onclick="closeDrawer()">✕ esc</button>
<h1 style="font-size:20px">${sym} <span class="pill" style="border-color:${TC[r.tag]||'#475569'};color:${TC[r.tag]||'#94a3b8'};margin-left:6px">${r.tag||''}</span>${r.veto?' <span class="badge b-red">VETOED</span>':''}</h1>
<div class="dim" style="font-size:12.5px;margin:4px 0 14px">${esc(r.company||'')} · ${esc(r.ind||'')}${r.tier?' · <b style="color:'+(TIERC[r.tier]||'#94a3b8')+'">'+r.tier+'-cap</b>'+(r.mcap?' '+fmtCr(r.mcap):''):''} · RS percentile ${r.rs??'—'} · conviction ${r.score??(D.details[sym]&&D.details[sym].score!=null?D.details[sym].score+(D.details[sym].label==='Technical Read'?' (technical read)':''):'—')}${r.arch?' · '+esc(r.arch):''}</div>
${planSection(sym,r)}
${whySection(sym)}
<div id="dchart" style="height:300px;margin-top:14px">${hasOhlc?'':'<div class="quiet">chart not cached for this name yet — it loads with the next scan alert or weekly refresh (or run: python scripts/enrich.py '+sym+')</div>'}</div>
${newsSection(sym)}
<div class="minis">
<div class="mini"><h3>Quarterly net profit (₹ Cr per quarter)</h3>${miniBars(f.q_labels||[],f.np||[])}</div>
<div class="mini"><h3>Operating margin % (quarterly)</h3>${miniLine(f.opm,'#5aa2ff','OPM %',f.q_labels)}</div>
<div class="mini"><h3>Borrowings ₹ Cr (yearly — falling = deleveraging)</h3>${miniLine(f.debt,'#fbbf24','debt',f.bs_labels)}</div>
<div class="mini"><h3>Shareholding % (quarterly)</h3>${miniLine(f.prom,'#a78bfa','Promoter',f.sh_labels)}${miniLine(f.fii,'#34d399','FII',f.sh_labels)}${miniLine(f.dii,'#5aa2ff','DII',f.sh_labels)}</div>
</div>`;
$('#ovl').classList.add('show');d.classList.add('open');
if(hasOhlc){const c=mkChart($('#dchart'),300);
const cs=c.addCandlestickSeries({upColor:'#34d399',downColor:'#f87171',borderVisible:false,wickUpColor:'#34d399',wickDownColor:'#f87171'});
const data=D.ohlc[sym];cs.setData(data.map(p=>({time:p[0],open:p[1],high:p[2],low:p[3],close:p[4]})));
c.addLineSeries({color:'#a78bfa',lineWidth:1}).setData(sma(data,50));
c.addLineSeries({color:'#fbbf24',lineWidth:1}).setData(sma(data,150));
const vol=c.addHistogramSeries({priceScaleId:'v',color:'#33415577'});
c.priceScale('v').applyOptions({scaleMargins:{top:.82,bottom:0}});
vol.setData(data.map(p=>({time:p[0],value:p[5],color:p[4]>=p[1]?'#34d39944':'#f8717144'})));
const pos=D.positions.find(p=>p.sym===sym);
if(pos){cs.createPriceLine({price:pos.stop,color:'#f87171',lineStyle:2,title:'stop'});
cs.createPriceLine({price:pos.be,color:'#fbbf24',lineStyle:2,title:'b/e'});
cs.createPriceLine({price:pos.partial,color:'#34d399',lineStyle:2,title:'partial 2.5R'});}
c.timeScale().fitContent();}};
window.closeDrawer=function(){$('#drawer').classList.remove('open');$('#ovl').classList.remove('show');};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();});

/* command palette — Ctrl+K or / from anywhere; type, arrows, Enter -> drawer */
(function(){
const pal=$('#pal'),q=$('#palq'),list=$('#pallist');let idx=0,matches=[];
const open=()=>{pal.classList.add('show');q.value='';filter('');setTimeout(()=>q.focus(),30)};
const close=()=>pal.classList.remove('show');
window.openPalette=open;
const filter=s=>{s=s.trim().toUpperCase();
 matches=(s?D.rows.filter(r=>r.sym.includes(s)||r.company.toUpperCase().includes(s)):D.rows.filter(r=>r.score!=null)).slice(0,40);
 idx=0;render();};
const render=()=>{list.innerHTML=matches.length?matches.map((r,i)=>`<div class="palrow${i===idx?' on':''}" data-i="${i}">
 <span class="sym">${r.sym}</span>
 <span class="dim" style="font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1">${esc(r.company)}</span>
 ${r.score!=null?`<b class="mono" style="font-size:12px">${r.score}</b>`:''}
 <span class="pill" style="border-color:${TC[r.tag]||'#475569'};color:${TC[r.tag]||'#94a3b8'}">${r.tag||''}</span></div>`).join('')
 :'<div class="palempty">No match among the 611 watched stocks.</div>';
 list.querySelectorAll('.palrow').forEach(el=>el.onclick=()=>{close();openDrawer(matches[+el.dataset.i].sym)});
 const on=list.querySelector('.palrow.on');if(on)on.scrollIntoView({block:'nearest'});};
q.oninput=()=>filter(q.value);
document.addEventListener('keydown',e=>{
 const typing=/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName);
 if((e.ctrlKey&&e.key.toLowerCase()==='k')||(e.key==='/'&&!typing&&!pal.classList.contains('show'))){
  e.preventDefault();open();return;}
 if(!pal.classList.contains('show'))return;
 if(e.key==='Escape')close();
 else if(e.key==='ArrowDown'){e.preventDefault();idx=Math.min(idx+1,matches.length-1);render();}
 else if(e.key==='ArrowUp'){e.preventDefault();idx=Math.max(idx-1,0);render();}
 else if(e.key==='Enter'&&matches[idx]){close();openDrawer(matches[idx].sym);}});
pal.onclick=e=>{if(e.target===pal)close();};
})();

/* positions */
function drawPositions(){window._pos=1;const w=$('#poswrap');
const hdr='<div class="card" style="padding:12px 20px;margin-top:16px"><h2 style="margin:0">Real positions &mdash; your actual money (positions.csv)</h2></div>';
if(!D.positions.length){w.innerHTML=hdr+'<div class="card quiet">No real positions tracked.</div>';return;}
w.innerHTML=hdr+D.positions.map(p=>{const prog=Math.max(0,Math.min(1,(p.last-p.stop)/(p.partial-p.stop)))*100;
return `<div class="card"><div class="posrow"><b style="font-size:16px" class="sym">${p.sym}</b>
<span style="color:${p.pnl>=0?'#34d399':'#f87171'};font-weight:800;font-family:var(--mono)">${p.pnl>0?'+':''}${p.pnl}%</span></div>
<div class="posrow dim"><span>${p.shares} shares @ ${p.entry}</span><span>last ${p.last}</span></div>
<div class="track"><div class="trackfill" style="width:${prog}%"></div></div>
<div class="posrow" style="font-size:11px"><span style="color:#f87171">stop ${p.stop}</span><span style="color:#fbbf24">b/e ${p.be}</span><span style="color:#34d399">partial ${p.partial}</span></div>
<div style="height:240px;margin-top:12px" id="pc_${p.sym}"></div>
<div class="dim" style="font-size:11px;margin-top:6px">${esc(p.notes)}</div></div>`}).join('');
D.positions.forEach(p=>{const data=D.ohlc[p.sym];if(!data||data.length<10)return;
const c=mkChart(document.getElementById('pc_'+p.sym),240);
const cs=c.addCandlestickSeries({upColor:'#34d399',downColor:'#f87171',borderVisible:false,wickUpColor:'#34d399',wickDownColor:'#f87171'});
cs.setData(data.map(q=>({time:q[0],open:q[1],high:q[2],low:q[3],close:q[4]})));
cs.createPriceLine({price:p.stop,color:'#f87171',lineStyle:2,title:'stop'});
cs.createPriceLine({price:p.be,color:'#fbbf24',lineStyle:2,title:'b/e'});
cs.createPriceLine({price:p.partial,color:'#34d399',lineStyle:2,title:'partial'});
cs.createPriceLine({price:p.entry,color:'#94a0b0',lineStyle:3,title:'entry'});
c.timeScale().fitContent();});}

/* journal */
$('#jstats').innerHTML=[['Signals logged',D.journal_total??D.journal.length,'Every alert since 2026-07-05, append-only.'],
['Open',D.outcomes.open??'—','Buy signals still tracking against their suggested stops.'],
['Stopped',D.outcomes.stopped??'—','Signals that hit the suggested stop (-1R, closed).'],
['Expectancy to date',D.outcomes.exp!=null?D.outcomes.exp+'R':'—','Forward, unfakeable. The gate for real capital: within ~50% of the +1.67R backtest at meaningful sample size.']]
.map(k=>`<div class="kpi"><span>${k[0]}<span class="info" data-tip="${esc(k[2])}">?</span></span><b>${k[1]}</b></div>`).join('');
const JK={'BUY CANDIDATE':'#34d399','RE-ENTRY WINDOW':'#a78bfa','WATCH CLOSELY':'#5aa2ff','EXIT WARNING':'#f87171','MANAGE':'#fbbf24'};
$('#jbody').innerHTML=D.journal.length?D.journal.map(j=>`<tr><td class="dim mono">${j.d}</td><td class="sym">${j.sym}</td><td><span class="pill" style="border-color:${JK[j.kind]||'#475569'};color:${JK[j.kind]||'#94a3b8'}">${esc(j.kind)}</span></td><td class="dim">${j.old&&j.old!=='nan'?esc(j.old)+' → ':''}${esc(j.new)}</td></tr>`).join(''):'<tr><td colspan="4" class="quiet">Journal is empty — it fills automatically as real alerts fire (a synthetic test entry was removed in the 2026-07-07 audit).</td></tr>';

/* buy-signal scorecard — same name re-alerting across nights is ONE story:
   the newest row is the live read, earlier rows get a ↻ marker + muted style
   (each stays a real journaled signal — the record never shrinks).
   Conv numbers at <60% data coverage carry a ° = "technical read". */
$('#scorebody').innerHTML=(D.scorecard&&D.scorecard.length)?D.scorecard.map(s=>{
const rc=s.r==null?'':s.r>0?'#34d399':s.r<0?'#f87171':'#94a0b0';
const st=s.status==='stopped'?'#f87171':s.status==='open'?'#34d399':'#64748b';
const tread=s.conv!=null&&s.cov!=null&&s.cov<60;
const convCell=s.conv==null?'':tread?`<span data-tip="Technical read — only ${s.cov}% of the 8 scored questions had data (fundamentals unavailable at alert time). Not comparable with full-coverage conviction scores.">${s.conv}<span style="color:#fbbf24">°</span></span>`:s.conv;
const reBadge=s.re?` <span class="pill" style="border-color:#a78bfa66;color:#a78bfa;font-size:9px" data-tip="Same name re-alerted later — the newest row above is the live read; this is the earlier signal, kept for the honest track record.">↻ ${s.re===1?'earlier alert':'earlier ×'+s.re}</span>`:'';
return `<tr onclick="openDrawer('${s.sym}')"${s.re?' style="opacity:.55"':''}><td class="dim mono">${s.d}</td><td class="sym">${s.sym}${reBadge}</td>
<td class="dim" style="font-size:11px">${s.kind==='BUY CANDIDATE'?'BUY':'RE-ENTRY'}</td>
<td class="mono">${convCell}</td><td class="mono">${s.entry??''}</td><td class="mono dim">${s.stop??''}</td>
<td class="mono" style="color:${s.ret>0?'#34d399':s.ret<0?'#f87171':''}">${s.ret!=null?(s.ret>0?'+':'')+s.ret+'%':''}</td>
<td class="mono" style="color:${rc};font-weight:700">${s.r!=null?(s.r>0?'+':'')+s.r+'R':''}</td>
<td class="mono dim">${s.maxr!=null?'+'+s.maxr+'R':''}</td>
<td><span class="pill" style="border-color:${st};color:${st}">${esc(s.status)}</span></td></tr>`}).join('')
:'<tr><td colspan="10" class="quiet">No buy signals tracked yet.</td></tr>';

/* paper book */
(function(){const P=D.paper||{};
const k=[['Net gain',(P.net!=null?(P.net>0?'+':'')+fmtNum(P.net)+' ₹':'—'),(P.net_pct!=null?'Realized + unrealized, as % of the ₹10L notional book: '+(P.net_pct>0?'+':'')+P.net_pct+'%':'Realized + unrealized on the ₹10L notional book.')],
['Realized',(P.realized!=null?(P.realized>0?'+':'')+fmtNum(P.realized)+' ₹':'—'),'Booked on exits only.'],
['Unrealized',(P.unrealized!=null?(P.unrealized>0?'+':'')+fmtNum(P.unrealized)+' ₹':'—'),'Open positions, mark-to-market.'],
['Open / pending',((P.open||[]).length)+' / '+((P.pending||[]).length),'Open positions / verdicts awaiting their next-session fill.']];
$('#paperkpi').innerHTML=k.map(x=>`<div class="kpi"><span>${x[0]}<span class="info" data-tip="${esc(x[2])}">?</span></span><b style="color:${String(x[1]).startsWith('+')?'#34d399':String(x[1]).startsWith('-')?'#f87171':'inherit'}">${x[1]}</b></div>`).join('');
let h='';
if((P.open||[]).length){h+=`<table style="margin-bottom:14px"><thead><tr><th>Symbol</th><th>Verdict</th><th>Entered</th><th>Entry ₹</th><th>Stop</th><th>Last</th><th>Shares</th><th>P&amp;L ₹</th><th>P&amp;L %</th></tr></thead><tbody>`+
P.open.map(p=>`<tr onclick="openDrawer('${p.sym}')"><td class="sym">${p.sym}</td>
<td class="dim" style="font-size:11.5px">${esc(p.verdict)}</td><td class="dim mono">${p.entered}</td>
<td class="mono">${p.entry}</td><td class="mono" style="color:#f87171">${p.stop}</td><td class="mono">${p.last}</td>
<td class="mono">${p.shares}</td>
<td class="mono" style="color:${p.pnl>=0?'#34d399':'#f87171'};font-weight:700">${p.pnl>0?'+':''}${fmtNum(p.pnl)}</td>
<td class="mono" style="color:${p.pnl_pct>=0?'#34d399':'#f87171'}">${p.pnl_pct>0?'+':''}${p.pnl_pct}%</td></tr>`).join('')+'</tbody></table>';}
if((P.pending||[]).length)h+='<div style="font-size:12.5px;margin-bottom:12px"><span class="axis">AWAITING FILL (next session open)</span><br>'+
P.pending.map(p=>`<span class="chip" style="border-color:#fbbf24"><b style="color:#fbbf24">${p.sym}</b><span>${esc(p.verdict)} · ${p.d}</span></span>`).join('')+'</div>';
if((P.ledger||[]).length){h+=`<div class="axis" style="margin:6px 0">RECENT PAPER FILLS</div><table><thead><tr><th>Date</th><th>Symbol</th><th>Action</th><th>Lot</th><th>Shares</th><th>Price</th><th>P&amp;L</th><th>Reason</th></tr></thead><tbody>`+
P.ledger.map(l=>`<tr><td class="dim mono">${l.d}</td><td class="sym">${l.sym}</td>
<td><span class="pill" style="border-color:${l.action==='BUY'?'#34d399':l.action==='SELL'?'#f87171':'#64748b'};color:${l.action==='BUY'?'#34d399':l.action==='SELL'?'#f87171':'#94a3b8'}">${l.action}</span></td>
<td class="dim">${esc(l.lot)}</td><td class="mono">${l.shares||''}</td><td class="mono">${l.price||''}</td>
<td class="mono" style="color:${l.pnl>0?'#34d399':l.pnl<0?'#f87171':''}">${l.pnl!==''&&l.pnl!=null?fmtNum(l.pnl):''}</td>
<td class="dim wrap" style="font-size:11px">${esc(l.reason)}</td></tr>`).join('')+'</tbody></table>';}
if(!h)h='<div class="quiet">No paper trades yet — the book opens automatically at the first analyst BUY verdict\'s next-session fill.</div>';
$('#paperbody').innerHTML=h;})();

/* AI picks */
const CONVC={HIGH:'#34d399',MEDIUM:'#fbbf24',LOW:'#f87171'};
function drawPicks(){window._picks=1;const w=$('#picksbody');const P=D.ai_picks||{};
if(!P.picks||!P.picks.length){w.innerHTML='<div class="card quiet">No AI picks yet. They generate weekly (or run scripts/ai_picks.py). The committee reviews the shortlist and selects 3-5 researched names.</div>';return;}
let h=`<div class="card" style="border-color:#fbbf2433"><h2 style="color:#fbbf24">Portfolio view</h2><div style="font-size:13.5px;line-height:1.7">${esc(P.portfolio_view||'')}</div><div class="axis" style="margin-top:8px">generated ${esc(P.generated||'')} · model ${esc(P.model||'')}</div></div>`;
P.picks.forEach((p,i)=>{const m=p.meta||{};const pl=p.plan||{};const cc=CONVC[p.conviction]||'#94a0b0';
h+=`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px">
<div><span style="font-size:12px;color:#fbbf24;font-weight:700">PICK ${i+1}</span>
<b class="sym" style="font-size:18px;margin-left:8px">${p.symbol}</b>
<span class="dim" style="font-size:12.5px"> ${esc(m.company||'')} · ${esc(m.sector||'')}</span></div>
<div><span class="pill" style="border-color:${cc};color:${cc}">${p.conviction||''} conviction</span>
<span class="pill" style="border-color:#334155;color:#94a3b8;margin-left:6px">mech ${m.score??'—'} · RS ${m.rs??'—'}</span></div></div>
<div style="margin-top:11px;font-size:12.8px;line-height:1.6"><span class="axis">SELECTED BECAUSE</span><br>${esc(p.selected_because)}</div>`;
if(pl&&pl.shares_total)h+=`<div class="mini" style="border-color:#34d39933;margin-top:10px"><span class="axis" style="color:#34d399">MECHANICAL PLAN (not AI — the validated engine)</span><br>
<span style="font-size:13px">Buy <b>${pl.shares_total} sh</b> ≈ ₹${fmtNum(pl.position_value)} · entry ~${pl.entry_price} · stop <span style="color:#f87171">${pl.stop_loss_price}</span> · partial <span style="color:#34d399">${pl.partial_price}</span>${pl.risk_scale<1?' · <span style="color:#fbbf24">HALF SIZE (defensive regime)</span>':''}</span></div>`;
else h+=`<div class="mini" style="border-color:#f8717144;margin-top:10px"><span class="axis" style="color:#f87171">NO MECHANICAL ENTRY PLAN</span> <span class="info" data-tip="The risk engine skips this name: its ATR-based stop would exceed the 12% hard cap — too volatile to size cleanly (Design Law #7). Watch only, not a buy.">?</span></div>`;
h+=`<details class="actrest"><summary>Full research — thesis, catalyst, management, risks</summary>
<div style="display:grid;grid-template-columns:1fr;gap:10px;font-size:12.8px;line-height:1.65;padding:8px 0 4px">
<div><span class="axis">THESIS</span><br>${esc(p.thesis)}</div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">
<div><span class="axis" style="color:#34d399">CATALYST</span><br>${esc(p.catalyst)}</div>
<div><span class="axis" style="color:#a78bfa">MANAGEMENT & QUALITY</span><br>${esc(p.management)}</div></div>
<div><span class="axis" style="color:#f87171">KEY RISKS</span><br>${esc(p.risks)}</div>
<div><span class="axis">WATCH FOR</span> ${esc(p.watch_for)}</div></div></details>
<div style="margin-top:10px" id="pick_${p.symbol}"></div></div>`;});
w.innerHTML=h;
P.picks.forEach(p=>{const data=D.ohlc[p.symbol];if(!data||data.length<10)return;
const c=mkChart(document.getElementById('pick_'+p.symbol),200);
const cs=c.addCandlestickSeries({upColor:'#34d399',downColor:'#f87171',borderVisible:false,wickUpColor:'#34d399',wickDownColor:'#f87171'});
cs.setData(data.map(q=>({time:q[0],open:q[1],high:q[2],low:q[3],close:q[4]})));
c.addLineSeries({color:'#fbbf24',lineWidth:1}).setData(sma(data,150));
if(p.plan&&p.plan.stop_loss_price)cs.createPriceLine({price:p.plan.stop_loss_price,color:'#f87171',lineStyle:2,title:'stop'});
c.timeScale().fitContent();});}

/* run panel — lights up ONLY when served by scripts/dashboard_server.py.
   Opened as a plain file (file://) the fetch fails and the panel stays
   hidden, so dashboard.html keeps working standalone. The AI committee is
   not runnable from here at all (credit guard lives server-side too). */
(async()=>{
 let st;
 try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)return;st=await r.json();}
 catch(e){return}
 $('#runpanel').style.display='block';
 const btns=[...document.querySelectorAll('.runbtn[data-job]')],status=$('#runstatus');
 let baseMtime=st.dashboard_mtime,timer=null;
 const render=s=>{
  btns.forEach(b=>b.disabled=s.running);
  if(s.running){
   status.innerHTML=`<span class="runlive">&#9679; ${esc(s.job)} running since ${esc(s.started_at)}</span>`+
    `<div class="runlog">${esc((s.log||[]).slice(-14).join('\n'))}</div>`;
   const lg=status.querySelector('.runlog');lg.scrollTop=lg.scrollHeight;
  }else if(s.finished_at){
   const fresh=s.dashboard_mtime>baseMtime;
   status.innerHTML=(s.exit_ok
    ?`<span style="color:var(--grn)">&#10003; ${esc(s.job)} done at ${esc(s.finished_at)}</span>`
    :`<span style="color:var(--red)">&#10007; ${esc(s.job)} FAILED at ${esc(s.finished_at)}</span>`+
     `<div class="runlog">${esc((s.log||[]).slice(-14).join('\n'))}</div>`)+
    (fresh?`<button class="runbtn" style="margin-top:7px" onclick="location.reload()">&#8635; Reload fresh data</button>`:'');
  }else status.textContent='';
 };
 const poll=async()=>{
  try{const q=await fetch('/api/status',{cache:'no-store'});st=await q.json();render(st);
   if(!st.running&&timer){clearInterval(timer);timer=null;}}
  catch(e){if(timer){clearInterval(timer);timer=null;}
   status.innerHTML='<span style="color:var(--red)">server stopped</span>';}
 };
 render(st);
 if(st.running)timer=setInterval(poll,2000);
 btns.forEach(b=>b.onclick=async()=>{
  if(!confirm('Run "'+b.textContent.trim().replace(/^\S+\s/,'')+'" now?'))return;
  baseMtime=st.dashboard_mtime;
  const q=await fetch('/api/run/'+b.dataset.job,{method:'POST'});
  if(q.status===409){alert('A job is already running — wait for it to finish.');return;}
  if(!timer)timer=setInterval(poll,2000);
  poll();
 });
})();
</script></body></html>"""


if __name__ == "__main__":
    build()
